### ISSUE TITLE
Ability to define class names

### ISSUE THREAD

**Issue by massive** [dollarshaveclub/stickybits#102]
Thanks for the great plugin!

We are using css modules, which basically manages class names to avoid name conflicts. Therefore, it would be useful to be able to define the class names by yourself. 

As far as I can see from the source, this is not currently possible?

As an example:

```js
import styles from './styles.module.css';
// ...
stickybits(element, { useStickyClasses: true, classNames: { isStuck: styles.isStuck } });

**Comment by yowainwright** [comment]
Will be working on this ASAP. ~Thanks for your note.

**Comment by yowainwright** [comment]
@massive done! Sorry for the wait. 👌
