### ISSUE TITLE
Edge / IE11 ignoring offset

### ISSUE THREAD

**Issue by daanvosdewael** [dollarshaveclub/stickybits#104]
First off, many thanks for maintaining this library.

I'm currently in the process of implementing Stickybits into a project. The HTML structure is roughly setup like this: [jsbin](https://jsbin.com/sulexo/edit?html,css,js,output).

The desired effect is that the red block sticks to the fixed header when you scrolled passed the full width orange block.

With Windows Edge & IE11 the red block goes under the fixed header, ignoring the offset specified by `stickyBitStickyOffset`.

Can you help me?

**Comment by yowainwright** [comment]
@daanvosdewael Yup! I'm working on a new iteration of Stickybits to more thoughtfully fix that. 

I'm hoping to get it out in the next week or so—just working on normal work stuff as well.

**Comment by yowainwright** [comment]
@daanvosdewael sorry it's taken a bit for the update. I hope to have an update that will address most of the issues in Stickbits asap—including yours. The update involves me writing must more in-depth tests and a bit of re-architecting to optimally address requests. ~Thanks

**Comment by yowainwright** [comment]
@here adding more tests to address issues. Hopefully by Wednesday!

**Comment by yowainwright** [comment]
This issue has been fixed according to tests. Please confirm with codepens otherwise. ~Thanks!
