### ISSUE TITLE
Sticky Classes adding unexpectedly when one parent has multiple same class sticky children

### ISSUE THREAD

**Issue by yaodingyd** [dollarshaveclub/stickybits#105]
_Test case:_
[http://jsfiddle.net/Lyx94mk1/](http://jsfiddle.net/Lyx94mk1/)

_Expected:_
[http://jsfiddle.net/w8p67epb/](http://jsfiddle.net/w8p67epb/)

I think this is because of using parent to determine whether to adding sticky classes, and because they have the same parent, when the first one gets sticky, all the rest gets "sticky" too, even though they are not.

I believe this is a big implementation difference with `fixed-sticky` as the latter uses each element offset to determine sticky. If this is intended, it might be good to highlight that, for same class children, each one needs its own parent in documentation.

**Comment by yowainwright** [comment]
@yaodingyd sorry it's taken a bit to respond. I hope to have an update that will address most of the issues in Stickbyt asap—including yours. The update involves me writing must more in-depth tests.

**Comment by yaodingyd** [comment]
@yowainwright  Thank you for your amazing work!

**Comment by yowainwright** [comment]
@here adding more tests to address issues. Hopefully by Wednesday!

**Comment by yowainwright** [comment]
@yaodingyd I will add your notes to a docs folder tomorrow. I would appreciate your feedback if you have time.

**Comment by yaodingyd** [comment]
@yowainwright Definitely! Thank you!

**Comment by yowainwright** [comment]
@yaodingyd what do you think? 

https://github.com/dollarshaveclub/stickybits/wiki/Understanding-Stickybits-and-Position-Sticky

**Comment by yaodingyd** [comment]
@yowainwright LGTM. Thank you!

**Comment by yowainwright** [comment]
Thanks @yaodingyd
