### ISSUE TITLE
Sticky classes adding unexpectedly with changed parent height

### ISSUE THREAD

**Issue by yaodingyd** [dollarshaveclub/stickybits#106]
_test case_
[http://jsfiddle.net/L1j6vb5z/](http://jsfiddle.net/L1j6vb5z/)

This might be a duplicate with #74.

You can see that the all 4 sticky elements don't get the class right, because there are lazy-loaded images and parent height keeps changed. But the conditions for determining sticky or not only happens once in initialization.

**Comment by yowainwright** [comment]
Duplicate of #74
