### ISSUE TITLE
Library not working (IE11)

### ISSUE THREAD

**Issue by jg** [dollarshaveclub/stickybits#118]
Went through a few of examples on the website [1], none of them work in IE11. The library itself isn't working there either, tried it in a separate project. 

IE 11.0.9600.18792
 
[1] https://dollarshaveclub.github.io/stickybits/

**Comment by yowainwright** [comment]
@jg The landing pages uses an older version of Stickybits. I will update that soon. 

I tested most of the demos in IE. Could you share errors? Or console.logs? Or screen shots?

```javascript
var stickybit = stickybits('[a selector]');
console.log(stickybit);
```
Thanks for the note! 🙏

**Comment by jg** [comment]
For a simple test case i forked your basic example from the site & copied over the src/stickybits.js code from github there, see [1]. It works in chrome, doesn't work in IE11. No errors in IE11 console

[1] https://codepen.io/anon/pen/EwXrdw

**Comment by yowainwright** [comment]
`src/stickybits.js` has ES6—which won't work in IE. 

I just tested again in IE again and the example I looked at—worked. 

Have you tried using a `dist` version of Stickybits?

**Comment by jg** [comment]
I updated the codepen to use the dist version now. Same thing happens in IE11 @ browserstack & locally. Chrome/firefox still working fine.

Can you confirm the codepen below uses the library correctly? 

https://codepen.io/anon/pen/EwXrdw

**Comment by yowainwright** [comment]
@jp you were right. Thank you so much! 

There was a Rollup Babel transpilation issue. 

I'm fixing it now. In the meantime, you could use an older version of the plugin.

**Comment by yowainwright** [comment]
@jg I'm updating all of the examples right now. Thanks!

~ The landing page will come tomorrow.
