### ISSUE TITLE
A destroy function to stop running the script?

### ISSUE THREAD

**Issue by Inayat-C** [dollarshaveclub/stickybits#120]
Hi,

First of all, thank you very much for your efforts in creating & maintaining this library, it works very well.

My issue is probably more of a request rather an issue with the library, but i was wondering if there is currently a way to stop running the script under certain conditions.

For example, i call stickybits() when my window size > 960. 

I then have a resize event which i would like to destory the stickybits() function if screen width < 960 and re-initialise when i go back up to 960. So it would be very useful to have a destroy and re-initialise methods.

**Comment by yowainwright** [comment]
Hey @Inayat-C!

Thanks! 

There is a method that does that. It is called `.remove()`. There is an example with a live codepen link in the `readme`.

**Comment by Inayat-C** [comment]
Hi, 

did you mean `.cleanup()`? as i can't find an instance of `.remove()`.

**Comment by yowainwright** [comment]
@Inayat-C yes! 

Thanks for correcting me! 😊

Please close this issue if we’ve resolved your question!
