### ISSUE TITLE
parentClass is always applied

### ISSUE THREAD

**Issue by kapouer** [dollarshaveclub/stickybits#123]
Setting parentClass to null or to empty string or false (your choice) should prevent stickybits from adding a class to the parent node [here](https://github.com/dollarshaveclub/stickybits/blob/72f3ece89320263b65bd1bf769a23d74ab03586c/src/stickybits.js#L60).

**Comment by yowainwright** [comment]
@kapouer to make sure I'm clear on the issue—what happens when you add an empty string?

```javascript
stickybits('selector', {parentClass: ''})
``` 

Also, why is the CSS class an issue? 

~Thanks!

**Comment by kapouer** [comment]
I'm doing
```
var sticky = stickybits('element-sticky', {
	stickyClass: 'is-sticky',
	parentClass: '',
	useStickyClasses: true // no classes are added if this isn't set
});
```
and document.body gets ` js-stickybit-parent`.
It's a minor bug, but a bug nonetheless. It pollutes attributes for no reason.

**Comment by yowainwright** [comment]
@kapouer that is interesting. I will look into it ASAP. 🙏

**Comment by yowainwright** [comment]
Added to [quirks](https://github.com/dollarshaveclub/stickybits/wiki/Quirks). 🙏
