### ISSUE TITLE
isSticky stays true even if i scroll back to the top

### ISSUE THREAD

**Issue by kapouer** [dollarshaveclub/stickybits#124]
The sticky is at
```<body><div class="stickit"></div>...</body>```
If i scroll down, stickyClass is added to the dom node.
However if i scroll back to the top, the class is not removed because of the test at:
https://github.com/dollarshaveclub/stickybits/blob/72f3ece89320263b65bd1bf769a23d74ab03586c/src/stickybits.js#L269

**Comment by yowainwright** [comment]
@kapouer could you provide an example to reference? ...So we can work on this together.

~Thanks!

**Comment by kapouer** [comment]
https://codepen.io/kapouer/pen/yzPWXG
I realized it's not only a matter of being the first child or not.
