### ISSUE TITLE
add possibility to update the parent's height (the stop parameter) after instance creation

### ISSUE THREAD

**Issue by oussa** [dollarshaveclub/stickybits#132]
Hello,

When I first used stickybits, I spent a lot of time trying to figure out why does the switch from `is-sticky` to `is-stuck` happen before reaching the parent's end.

After some investigation, I found out that the cause is that the parent in my case contains images that were not loaded yet, causing a fake **much smaller height** for the parent, and which once loaded completely would cause the whole UI to look weird, navbar gets stuck too early..

Possible solution to fix this is to not trust the parent height value on the moment of creation or to be able to override it on the created instance value..

**Comment by yowainwright** [comment]
@oussa thanks for you insight! 

The API can account for that but I'm yet to do a demo. I'm going to close this ticket as it will be documented in issue #100 

~Thanks again 🙏
