### ISSUE TITLE
Workaround for Firefox not supporting position: sticky on table elements

### ISSUE THREAD

**Issue by EmilStenstrom** [dollarshaveclub/stickybits#143]
[Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=975644) does not support position: sticky on table elements. But there is nothing in stickybits to prevent this, so calling stickybits("thead th") looks like it works (all th:s get position: sticky), it just doesn't work when scrolling.

Are you open to adding a fix for this in stickybits?

I can think of two ways of doing this:
* Detecting that someone is targeting a table element (table, thead, tbody, tfoot, tr, td, th...) and fall back to position: fixed.
* Add a way to disable the feature check entirely so position: sticky is never used.

Thanks for all your hard work!

**Comment by yowainwright** [comment]
@EmilStenstrom thanks for your detailed question! 

I don't think Stickybits should supply actual code to protect against elements, like `<table>` elements not working in Firefox. Adding features like that would cause the KB size of Stickybits to grow a lot. It would lead to unexpected other issues (fix one thing and break another). It would make the code less readable.  

I think a solution would be to add a note to the [Wiki](https://github.com/dollarshaveclub/stickybits/wiki/Debugging-Stickybits) with an example of how to work around the issues. Would you help me do that?! 🙏

...I think that all that might need to be done for `<table>` elements to work with Stickybits is to change their `default css display property`. A `<table>`'s default `display` is `display: table`. Does Stickybits work when the `<table>`'s display property is changed to `display: block`?

Thanks again!

**Comment by EmilStenstrom** [comment]
Hi! Thank for a quick reply! I've played around with display settings to work around the issues. The problem is that other issues pop up instead:

The trick I found used `tbody, thead tr { display: table }` and `thead { display: block; position: sticky; top 0}`. This works, but disconnects the thead from the tbody, so the table heading gets disconnected from the generated width of the actual content. You can work around that by setting the width of all the cells, but this is a hassle. I didn't find a workaround that didn't involve me rewriting the CSS of my tables at the same time...

To make sure the source code of stickybits is as small as possible, maybe my other suggestion would be a better fit? Disabling the feature check (with a user option) to make sure Firefox is treated as if it didn't have support for position: sticky at all. I tried monkey-patching definePosition, but had no luck there (my JS skills are from 10 years ago, so very rusty...).

Maybe that could be a way forward?

**Comment by yowainwright** [comment]
@EmilStenstrom thanks for thoughtful response! 

Could you supply a code example? 

Maybe I/you/someone can make it work and then add your notes to the wiki ...?

~Thanks again

**Comment by yowainwright** [comment]
@EmilStenstrom Here's a codepen. It looks like it works in Firefox. What are you seeing?

I'm totally open to misunderstanding something! ~Thanks

**Comment by EmilStenstrom** [comment]
@yowainwright Thanks for making an example, makes it much easier to talk about. As you have noticed, if you change an element from `display: table` to `display: block` (as you have with .child), it works in Firefox. Problem is, when you do that, that element stops behaving like a table element. Try adding another `<th>` to your example. Since it is `display: block` it gets rendered below the other `<th>`. This is probably fixable using some sort of flex magic, but this is where I ended up rewriting my table CSS, something I just don't want to do. 

I'm not sure there is an easy way to get this to work...

**Comment by EmilStenstrom** [comment]
Here's a sample page: https://codepen.io/EmilStenstrom/pen/QOWzgv - as soon as you change the display property of the th cells you break the whole table...

**Comment by yowainwright** [comment]
@EmilStenstrom I don't see this as a Stickybits issue—this issue will present itself with vanilla CSS and HTML. The original codepen that was posted shows that table elements can be worked around with Stickybits.

I appreciate the time that has been put into this issue. Now anyone that runs into a similar use case can find this issue and decide what to do—use Stickybits and change the `<td>` element's default CSS `display` property or come up with a different solution. 

THANK YOU! 🙏

**Comment by EmilStenstrom** [comment]
Thank you for taking the time to consider this!

**Comment by yowainwright** [comment]
@EmilStenstrom 🙌
