### ISSUE TITLE
Why Vertical Layout Positioning at the Bottom is so weird? 

### ISSUE THREAD

**Issue by iamdubx** [dollarshaveclub/stickybits#146]
I want to stick element at the bottom of the screen at `1em`.
This code from Docs doesn't do anything, literally `stickybits('.bit', {verticalPosition: 'bottom'})`

Then I found example on that page, that has ugly `style.top` calculation on every load.

Am I getting right - it is impossible to have `bottom: 1em` positioning with `stickybits`?

**Comment by yowainwright** [comment]
@iamdubx Stickybits contributors are open to a better solution to the example provided. 😊

Since the comments above do not define a problem—only opinions, this issue is being closed. 

Feel free to provide a PR if you come up with one.

~Thank you!

**Comment by iamdubx** [comment]
@yowainwright sorry, I didn't meant to offend anyone. I just trying to figure out how to use it? Never used `sticky` feature before, and it turns unexpectedly difficult to achieve such trivial task.
