### ISSUE TITLE
useStickyClasses without scroll event listener

### ISSUE THREAD

**Issue by dotmagic** [dollarshaveclub/stickybits#156]
I would be awesome if you could set the sticky class with `IntersectionObserver` and using scroll event listener only as a fallback.

There's a well written article how to implement it:
https://developers.google.com/web/updates/2017/09/sticky-headers

Alle major Browsers support already `IntersectionObserver`. I think will take a look how to implement this next weekend:
https://caniuse.com/#feat=intersectionobserver

**Comment by patrick-mcdougle** [comment]
FYI, IntersectionObserver doesn't quite help in edge cases like jump links. Something to consider. See https://github.com/w3c/IntersectionObserver/issues/258 for more info.

**Comment by dotmagic** [comment]
@patrick-mcdougle Oh, I wasn't aware about it.
Anyway. It's still useful to have a option to enable IntersectionObserver support aslong ist disabled by default.

**Comment by yowainwright** [comment]
@dotmagic have you done any hacking on this? No pressure! 😊 ...Just excited to see. Feel free to request reviews from me—if you're merging to your own repo, etc.

**Comment by yowainwright** [comment]
@dotmagic if you're going to work on this—re-open the issue. ~Thanks!!!

**Comment by dotmagic** [comment]
@yowainwright Sorry for late reply. Yes, I won't have time for the next 3 months.
