### ISSUE TITLE
Options `useStickyClasses` and `stickyBitStickyOffset` work wrong

### ISSUE THREAD

**Issue by serhiyzablotskiy** [dollarshaveclub/stickybits#159]
When I use `useStickyClasses` and `stickyBitStickyOffset` options together `stuckClass` is not added correctly:

When I changed 
` it.offset = scrollElOffset + p.stickyBitStickyOffset;`
to 
` it.offset = scrollElOffset - p.stickyBitStickyOffset;`
here
```
Stickybits.prototype.computeScrollOffsets = function computeScrollOffsets(item) {
...
it.stickyStart = stickyStart - p.stickyBitStickyOffset;
...
};
```
it starts work.

**Comment by yowainwright** [comment]
@serhiyzablotskiy thank you!!! I will look at your comments as soon as I can! 🙏

**Comment by serhiyzablotskiy** [comment]
Here is pull request to fix this: https://github.com/dollarshaveclub/stickybits/pull/161
