### ISSUE TITLE
IE11 Option `stickyBitStickyOffset`

### ISSUE THREAD

**Issue by rosivanov** [dollarshaveclub/stickybits#160]
case: IE11 + `stickyBitStickyOffset` 
pen: https://codepen.io/yowainwright/pen/YQZPqR
gif:
![bandicam-2017-11-22-04-46-46-394](https://user-images.githubusercontent.com/8172473/33110653-06b21824-cf52-11e7-9794-2aab96b99dfb.gif)

When the viewport top edge reaches `.main` , `.child` jumping 20px bottom.
I appreciate if you can conside this case.

**Comment by yowainwright** [comment]
I will look into this asap @rosivanov.

**Comment by rosivanov** [comment]
@yowainwright thanks

**Comment by rosivanov** [comment]
@yowainwright Yes generally it works. CRs what is this ?

**Comment by yowainwright** [comment]
@rosivanov my mistake—"CRs" = Code Reviews. ☺️

**Comment by rosivanov** [comment]
@yowainwright Okay, will try to figure out something.

**Comment by yowainwright** [comment]
@rosivanov in my opinion, if it is a big deal for your use-case in IE 11, I would write something custom. There will/would be a lot of extra code to seek perfection in each older browser and this would simultaneously decrease quality in newer browsers and **other** older browsers. 🙌

**Comment by rosivanov** [comment]
@yowainwright Thanks, it is not criticat case so i don't want waste your precious time :wink:
