### ISSUE TITLE
Shrinked header support: Add a `shrinkedHeaderCSSClass` for `useStickyClasses`?

### ISSUE THREAD

**Issue by jnachtigall** [dollarshaveclub/stickybits#169]
For adding a shrinked header, that is a header that get reduced in height (could a an css animation), it would be great if a `js-is-shrinked` css class could be added. 

At the moment there is `js-is-sticky` but this is added immediately, whereas for `js-is-shrinked` the css class would only be added after a certain `top` offset is passed. This would allow for nice (reduce/increase) header height animation to happen based on the scroll position.

Sure, one could add it's one scroll event listener but this stickybits already adds one, I guess it would be better to (re-)utilize this.

I tried looking into the code and guess something would need to be added to the `manageState` function but eventually gave up (too many 2-3 letter vars, not sure what the difference between `isSticky` scroll and `sticky` state is etc ;)

**Comment by yowainwright** [comment]
@jnachtigall thanks for your thoughtful insight!

I think the feature above steps a bit too far outside of what the plugin is supposed to do. 

That stated, it would definitely be a fun Codepen that I would like to see! If you make a Codepen with that feature or build off of what's there for Stickbybits to make a similar feature—I'd love to add it to our Wiki. 

~Thanks!

**Comment by jnachtigall** [comment]
@yowainwright Good idea, I can add a codepen, actually I just started doing so... But it would be great if you could add stickybits to cdnjs.com See https://stackoverflow.com/questions/44981404/how-do-i-upload-to-cdnjs#44981554 for how this can be done (I think it's better if you do it, since you are the maintainer). This would make it just easier to create the codepen (and would have other benefits like easier adaption, more options to install...)

Also I just noticed now that the other example codepens to have the lib added in the JS section. At first, I thought: "Howly cow, this is suppossed to be the "basic" example" when looking at https://codepen.io/yowainwright/pen/QdedaO Now I see where this comes from ;)
