### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by dotmagic** [dollarshaveclub/stickybits#171]
Could you please update the Changelog.md?

**Comment by yowainwright** [comment]
@dotmagic could you help me out? 🙏

**Comment by dotmagic** [comment]
@yowainwright Mmmm? It's just adding the changes from git history. I think you're the one who knows best what happened between the releases?

**Comment by yowainwright** [comment]
@dotmagic so you don't want to help out? I assume you can look at history and commit comments.

**Comment by dotmagic** [comment]
Haha, I just did and its slightly confusing. It seems the only changes between 2.0.6 -> 2.0.13 was:
* 2.0.7 Add es-check
* 2.0.13 Fix markdown issue in README.

The other releases just bump the version!? Am I missing something? You really want me to create a pull request for that?

**Comment by yowainwright** [comment]
Yes please! 

I'm not trying to sound rude. I would just like help. 

I would like to automate the `changelog.md`. If you would like to do that = event better!!! 

~Thanks again

**Comment by yowainwright** [comment]
@dotmagic SORRY! I will update this changelog. If you would like to PR to automate a changelog that would be awesome.

**Comment by jnachtigall** [comment]
@yowainwright Sorry, I cannot help here, but for automating the changelog generation you can use https://www.npmjs.com/package/release-it which does this among other things. It does not look difficult to setup, but I guess one needs npmjs and github permissions to actually do it.
