### ISSUE TITLE
Element doesn't stick when html overflow-x is set to hidden

### ISSUE THREAD

**Issue by ajithbhat** [dollarshaveclub/stickybits#173]
Hello,
We have a scenerio where overflow-x is set to hidden (line 4) on HTML tag of the page. With this being set, stickybits doesn't work. I have created a Pen on CodePen to demonstrate this. 

https://codepen.io/ajithbhat/pen/GOaqww

If, overflow-x is removed on the HTML tag, it works.

**Comment by yowainwright** [comment]
Hello @ajithbhat! Thanks for your issue. ☺️
- Note this issue within the [W3C Spec](https://github.com/w3c/csswg-drafts/issues/865)
