### ISSUE TITLE
Adding stickybits to a CDN, e.g. cdnjs.com?

### ISSUE THREAD

**Issue by jnachtigall** [dollarshaveclub/stickybits#183]
Hey, Spin-off of https://github.com/dollarshaveclub/stickybits/issues/169#issuecomment-349981530 ;)

It would be great if stickybits was on cdnjs.com See https://stackoverflow.com/questions/44981404/how-do-i-upload-to-cdnjs#44981554 for how this can be done (I think it's better if you do it, since you are the maintainer). This would make it just easier to create codepen and other examples (and would have other benefits like easier adaption, more options to install...)

Also I just noticed now that today's example codepens to have the lib added in the JS section. At first, I thought: "Howly cow, this is suppossed to be the "basic" example" when looking at https://codepen.io/yowainwright/pen/QdedaO without realising that this is just the pasted whole stickybits library and the example is just a single line at the very botton (only visible if you scroll down).

This being said, I have a running example a local Shrinked Sticky header based on stickybits but would be really great to not having to paste in the whole lib but being able to use a cdn for the codepen example. Thanks and enjoy the holidays :) 

I really like stickybits, well done!

**Comment by yowainwright** [comment]
@jnachtigall where is that example? 😃 

There is work involved in adding a repository to CDNJS—CDNJS is a large repo and is maintained by other people that must take time to CR, etc. Scripts can be added in Codepens and then re-used elsewhere so I think that is an option. I leave the code within the Codepen so that people can debug the library. 

If you'd like to own this issue (adding Stickybits to a CDN), that would be optimal. 

~Thanks

**Comment by yowainwright** [comment]
@jnachtigall we will see if this goes through. https://github.com/cdnjs/cdnjs/pull/12394

**Comment by DanielRuf** [comment]
unpkg should already deliver them ;-)

**Comment by DanielRuf** [comment]
https://unpkg.com/stickybits@2.1.1/dist/stickybits.js
https://unpkg.com/stickybits@2.1.1/dist/stickybits.min.js
https://unpkg.com/stickybits@2.1.1/dist/jquery.stickybits.js
https://unpkg.com/stickybits@2.1.1/dist/jquery.stickybits.min.js

**Comment by yowainwright** [comment]
Thanks @DanielRuf ! Also, https://github.com/cdnjs/cdnjs/pull/12409

**Comment by jnachtigall** [comment]
@yowainwright Here's the demo for a Shrinked Sticky Header using stickybits: https://codepen.io/nachtigall/pen/GQJWLz I would be happy if you review (fork/edit) it and link to it from the stickybits docs or README.

**Comment by yowainwright** [comment]
@jnachtigall thanks for the Codepen!

No need for jQuery or extra JS. https://codepen.io/yowainwright/pen/JpdVoX

**Comment by jnachtigall** [comment]
> No need for jQuery or extra JS

@yowainwright Well, depends on the use case. If you need to style anything *outside* of the sticky element when being sticky/shrinked than it is not sufficient to add a css class to just this element. That's why the original code adds a css class to `body`. 

This use case is not so uncommon. Based on experience I'd say 50:50. In half the use cases (bigger sites) theres is also some kind of element *outside* of header which is supposed to be shown/hidden or changed visually whenever there is a shrinked/sticky header or not. 

This was the reasoning for the more comprehensive extra js / jQuery. I do not know if it was possible to always attach a css class to, say, `body` - then of course it would be possible with vanilla stickybits and hence easier.

**Comment by DanielRuf** [comment]
> I do not know if it was possible to always attach a css class to, say, body

Personally I did it with vanilla JS in many projects in the past and it always worked. jQuery is just a framework.
