### ISSUE TITLE
Sticky nav inside on "header element", do not works.

### ISSUE THREAD

**Issue by jquimera** [dollarshaveclub/stickybits#195]
I'm trying to use Stickybits this way. But it's not working. Example below.

```
<header class="main-header">
	
	<div class="header-content">
		<h1>My Stick Nav</h1>
	</div>

	<nav id="my-stick-nav" class="main-nav">
		<ul>
			<li><a href="#">Home</a></li>
			<li><a href="#">Products</a></li>
			<li><a href="#">Services</a></li>
			<li><a href="#">About US</a></li>
			<li><a href="#">Blog</a></li>
			<li><a href="#">Contact</a></li>
		</ul>
	</nav>
	
</header>
```

**Comment by yowainwright** [comment]
Hey @jquimera could you provide an example in a codepen?

**Comment by jquimera** [comment]
yes, here: https://codepen.io/johnquimera/pen/EoOKoJ

**Comment by yowainwright** [comment]
@jquimera it doesn't have to do with the header element. It has to do with the way `position: sticky` works. 😊

https://codepen.io/yowainwright/pen/OzaRbe

**Comment by jquimera** [comment]
@yowainwright I understand, I wanted the "nav" inside the "header"

**Comment by hacknug** [comment]
@jquimera then you should probably make the whole header sticky. Remember that sticky-positioned items only get stuck inside their parent.
