### ISSUE TITLE
Any way to make this work with overflow: auto; ?

### ISSUE THREAD

**Issue by KyleVassella** [dollarshaveclub/stickybits#196]
I have a main theme `<div>` that has a style of `overflow: auto;` (and sometimes `overflow: hidden;`) that I can't make changes to.

Deep within this `<div style="overflow:auto;">` I have a `<nav>` element which I'm trying to make sticky w/ an offset of 100px. It doesn't work unless I change the aforementioned `<div>` to `overflow: visible;`

Can I keep this great great grandparent `<div>` set to `overflow: auto;` , and maybe do something to the direct parent of my sticky `<nav>`, or to the `<nav>` itself to make this work?

**Comment by yowainwright** [comment]
@KyleVassella please [checkout](https://github.com/dollarshaveclub/stickybits/issues/173) this issue. Thanks! 

---

https://github.com/dollarshaveclub/stickybits/issues/173
