### ISSUE TITLE
useStickyClasses False still adding classes

### ISSUE THREAD

**Issue by ggedde** [dollarshaveclub/stickybits#197]
Using 
`stickybits('.sticky');`
Or 
`stickybits('.sticky', { useStickyClasses: false });`
Still adds classes and changes classes when scrolling.

This is happening on Mac Chrome (63.0.3239.132)
It is not happening on FireFox.

Using @version v2.1.1

**Comment by yowainwright** [comment]
@ggedde darnit. Could you supply a codepen or url? ~Thanks

**Comment by ggedde** [comment]
Here you go:
https://codepen.io/anon/pen/aEPbXm

**Comment by yowainwright** [comment]
@ggedde darnit. That is no fun 😔. I will look into this as soon as I can.

**Comment by ggedde** [comment]
@yowainwright 
No worries.
Thanks

**Comment by hacknug** [comment]
I'm pretty sure I introduced this bug with my fix for the `cleanup` method. I'm gonna try to take a look at it now and will open a PR once it's done 😃

**Comment by hacknug** [comment]
@ggedde take a look at #198 and let me know if this fixes it for you without introducing any new issues lol

**Comment by yowainwright** [comment]
@ggedde thanks for catching this. This should be fixed. I will do visual checks today, close this issue and publish.

**Comment by ggedde** [comment]
@yowainwright 
Thanks, It is working now.
