### ISSUE TITLE
Trigger events when swapping sticky/stuck classes

### ISSUE THREAD

**Issue by hacknug** [dollarshaveclub/stickybits#213]
I think it would be useful to have Stickybits trigger its own events when it changes between the sticky/stuck classes. This way we could listen to them and trigger our own logic based on that.

Is this something that's already possible? Would this be useful to anyone else?

**Comment by yowainwright** [comment]
I built a prototype of this and realized it was slightly more code for this plugin which I've tried to maintain as at **"utility"** plugin.

**Comment by hacknug** [comment]
I'm all in for tiny plugins but I still believe this wouldn't add too much clutter and it would turn it into a much for useful utility. Let me know if you'd be open for a PR on this.

**Comment by yowainwright** [comment]
Okay, have a go! 👌

----

### Steps

- [ ] define event nomencalture
- [ ] write tests
- [ ] build feature
- [ ] update documentation
- [ ] add examples

----

### Shop talk

Below is a quick untested idea for how this could work. 

**Here's a potential pattern:**
```javascript
// something like this
const se = this.props.scrollEl
se.dispatchEvent(new Event('stickbits.isSticky'))
// other potential events
// se.dispatchEvent(new Event('stickbits.isStuck'))
// se.dispatchEvent(new Event('stickbits.unSticky'))
// se.dispatchEvent(new Event('stickbits.cleaned'))
```

**Events could trigger actions like so:**
```javascript
const someFunc = () => console.log('someFunc invoked')
document.querySelector('some el').addEventListener('stickybits.isSticky', someFunc)
```

**Comment by DanielRuf** [comment]
Definitely a good idea. Or using an observer may be also a solution but only for modern browsers in general.

**Comment by DanielRuf** [comment]
https://github.com/w3c/IntersectionObserver/blob/master/explainer.md
https://github.com/w3c/IntersectionObserver/tree/master/polyfill

**Comment by yowainwright** [comment]
@DanielRuf let's do a simple version then! I hesitated from adding the intersectionObserver as I see these as a utility plugin to support potentially more "antique" 😁 browsers. 

@hacknug are you going to go for it? ...Or maybe I can build the feature/tests and maybe you could do the demos? 😃

I think I could use events to support 2 other issues.

**Comment by DanielRuf** [comment]
> @hacknug are you going to go for it? ...Or maybe I can build the feature/tests and maybe you could do the demos? 😃
> 
> I think I could use events to support 2 other issues.

I guess this would be helpful in many scenarios.

Can we create a project and board to collect these issues and label the board with `custom events / event handlers`?

**Comment by hacknug** [comment]
@yowainwright I'll probably be able to take a look at this in a couple or three days as I am kinda busy with some projects where I'm not using Stickybits. If you prefer to do it yourself sooner, I'll take care of the demos once the work is done. Just let me know.

**Comment by yowainwright** [comment]
Cool, I can do that and then you can do the demos. 🙌

**Comment by yowainwright** [comment]
@DanielRuf yes, I'll do that right now.

**Comment by yowainwright** [comment]
@DanielRuf see the new milestone.

**Comment by DanielRuf** [comment]
Awesome, thanks =)

**Comment by yowainwright** [comment]
@hacknug @DanielRuf I worked on **events** a bit. I worked on **events** a bit when I was considering an event based API for Stickybits—but forgot. 😜

This is what I'm thinking for events based on my awareness today and before:
-  no events for sticky, stuck, notStuck
    - CSS classes intead
       - will add css classes for:
          - js-is-sticky--safe
            - new CSS class that will be calculation of the sticky calculation + the outerheight of the element so that user can do stuff with the header height, etc.
    - **REASON:** with many stickybits on a page, potentially with the same selector, this could be the nightmare that takes stickybits from being a utility to library with many more issues that will show up.
- events **only per document**
   - stickybits.change
      - will recalculate sticky start, stop

___

Feedback is appreciated!!!

**Comment by DanielRuf** [comment]
Or people should use mutation observers. Not yet sure here.

**Comment by yowainwright** [comment]
* https://github.com/dollarshaveclub/stickybits/pull/255

**Comment by yowainwright** [comment]
@hacknug I added the the new `js-is-sticky--change` css class.
