### ISSUE TITLE
Multiple instances example not working well in IE11

### ISSUE THREAD

**Issue by matthijs-bakker** [dollarshaveclub/stickybits#225]
Hi,

I noticed that the multiple instances example (as can be found here: https://codepen.io/yowainwright/pen/VPogaX) does not work well in IE11. The initial render is broke, after some scrolling everything seems to work fine.

Browser version: IE 11.125.16299.0
Screenshot of defect:

![image](https://user-images.githubusercontent.com/10942676/35806211-094010ba-0a7f-11e8-872a-829c574b17aa.png)

**Comment by yowainwright** [comment]
@matthijs-bakker feel free to look that this issue as well. I'm pretty busy for the next week/2 weeks. ~Thanks!

**Comment by DanielRuf** [comment]
The issue here is that is initially always set to `fixed` but need to be the initial / default relative property value.

**Comment by DanielRuf** [comment]
```
function Stickybits(target, obj) {
  var o = typeof obj !== 'undefined' ? obj : {};
  this.version = '"3.0.2"';
  this.userAgent = window.navigator.userAgent || 'no `userAgent` provided by the browser';
  this.props = {
    noStyles: o.noStyles || false,
    stickyBitStickyOffset: o.stickyBitStickyOffset || 0,
    parentClass: o.parentClass || 'js-stickybit-parent',
    scrollEl: o.scrollEl || window,
    stickyClass: o.stickyClass || 'js-is-sticky',
    stuckClass: o.stuckClass || 'js-is-stuck',
    useStickyClasses: o.useStickyClasses || false,
    verticalPosition: o.verticalPosition || 'top'
  };
  var p = this.props;
  /*
    define positionVal
    ----
    -  uses a computed (`.definePosition()`)
    -  defined the position
  */
  p.positionVal = this.definePosition() || 'fixed';
```

**Comment by matthijs-bakker** [comment]
Great! Thanks @yowainwright

**Comment by clucaseh** [comment]
Does the elements need to be in a flexbox for it to work properly in IE11
