### ISSUE TITLE
Demo broken in IE11 & 10

### ISSUE THREAD

**Issue by wolthers** [dollarshaveclub/stickybits#228]
https://codepen.io/yowainwright/pen/EXzJeb

Sidebar starts out as fixed
![image](https://user-images.githubusercontent.com/841834/35982956-497f49d8-0cf1-11e8-9555-0118f32812eb.png)

Also doesn't work if I remove the scrollEl option and remove overflow-y: on main. 

Is there a way to "refresh"? Doing that after initial load would probably solve it.

**Comment by wolthers** [comment]
Seems to be a problem with the ES module build. When i remove "module" from package.json so it uses `dist/stickybits.js` instead of `dist/stickybits.es.js` it works as expected on first load(?!)

**Comment by DanielRuf** [comment]
Hm,  ight be because how root is created. Probably an issue with `isWin`?

**Comment by yowainwright** [comment]
@wolthers @DanielRuf that means that issue was created in one of our last few versions (last week)—see the top of the readme for why. 

The good news is that  fix should be a minor logic revision. The bad news is that I'm super busy working on other projects for the next week/2 weeks. 

Can some take this issue?

**Comment by DanielRuf** [comment]
No problem, I'll do a git bisect, triage and fix it.

**Comment by wolthers** [comment]
Just to confirm - it works in 2.1.2. The demo I linked runs on 3.0.0 so it must have been introduced from 2.1.2 to 3.0.0

**Comment by yowainwright** [comment]
@DanielRuf thanks! 🙏 I like the updates that were made (the ternaries). 

It is probably just a minor logic tweak (hopefully).

**Comment by DanielRuf** [comment]
> Seems to be a problem with the ES module build. When i remove "module" from package.json so it uses dist/stickybits.js instead of dist/stickybits.es.js it works as expected on first load(?!)

Event with the normal version I see the issue.

**Comment by DanielRuf** [comment]
There are multiple factors. First the main element which is not supported by default in IE11. Second a missing `querySelector` call. And third a wrong position calculation.

> dist/stickybits.js instead of dist/stickybits.es.js

Attention, they do not use the same version.

**Comment by DanielRuf** [comment]
@wolthers So far I can not get the demo working on IE11 with the 2.1.2 version using document.querySelector. Please provide a codepen where it works like you say.

**Comment by wolthers** [comment]
Can't get the demo to work in IE either. 

What i wrote still holds true for me in my project. Just double checked. The `dist/stickybits.es.js` doesn't work but `dist/stickybits.js` does.

**Comment by DanielRuf** [comment]
> What i wrote still holds true for me in my project. Just double checked. The dist/stickybits.es.js doesn't work but dist/stickybits.js does.

Take a look at the files and the version strings in there ;-)

**Comment by DanielRuf** [comment]
Related: https://github.com/dollarshaveclub/stickybits/pull/229

**Comment by yowainwright** [comment]
@wolthers @DanielRuf this starter issue should be fixed as of 3.0.3. ~THANKS AGAIN! 🙏
