### ISSUE TITLE
Cleanup method?

### ISSUE THREAD

**Issue by rulych** [dollarshaveclub/stickybits#23]
Is there any way to stop and clean up an instance of stickybits? If not, it would be nice to add one. For example, if you want to use the stickybits within a React component, it would be good to be able to remove it (especially the event listener added by `manageStickiness()`) when the component is unmounted.

**Comment by yowainwright** [comment]
@rulych thanks for the comment! We have an issue setup for more framework/library support—like React. I will consider this feature very soon. If you'd like to help be a part of that—let me know. 🙌

**Comment by rulych** [comment]
I don't it's about framework/library support. The integration with React is already super simple. 👍

What I meant is that, after you use `stickybits()` somewhere, the event listener that is registered is never cleaned up. For example:
```
const myDiv = document.createElement('div');
document.body.appendChild(myDiv);
stickybits(myDiv);
myDiv.remove();
```

After executing this code, the `scroll` event listener remains there, even though it's useless now.

**Comment by yowainwright** [comment]
@rulych that's a great point! ~Thanks
