### ISSUE TITLE
Height changing sticky elements result in constant updates

### ISSUE THREAD

**Issue by padarom** [dollarshaveclub/stickybits#234]
I need to build a header that shrinks in size (by removing some elements, shrinking the logo within the header, ...) when stuck, so that it doesn't use as much screen real estate.

In my example I change the height for `.js-is-sticky` from 100 pixels to 50px. When just starting to scroll and the element just receives the `.js-is-sticky` class, it starts to quickly jump back and forth between having the class and having it removed, so that the element quickly updated between 100px and 50px in height.

Working fiddle: https://jsfiddle.net/ke5oLde6/2/

Is there any other way this height-changing behavior can be implemented correctly when using stickybits?

**Comment by yowainwright** [comment]
From what I understand, this could definitely be done and **not** with JavaScript—just html and css. 

The issue with the end result in the demo (thanks for the thoughtful demo by the way! 😊) is the way the html and css is structured. If stucture of the html and css is re-worked, then the desired outcome can be achieved! 💪

**Comment by padarom** [comment]
Could you perhaps point me in the right direction on how to change my structure? 

My use-case is a bit more complicated than what I linked, that's just the smallest possible example. For example I have up to two more elements that also need to be sticky, but underneath the (already sticky) main header. Pure HTML and CSS could potentially work with `position: sticky`, but then I'd need a polyfill for support, so I might as well use stickybits.

**Comment by yowainwright** [comment]
@padarom makes sense. This is a quick demo, https://codepen.io/yowainwright/pen/JpdVoX.

After closer inspection, I think with the event feature, Stickybits can provide better support.
