### ISSUE TITLE
Property scrollEl doesn't work

### ISSUE THREAD

**Issue by enheit** [dollarshaveclub/stickybits#237]
There is no possibility to use custom `scrollEl` the following issue is showing in the browser console.

`Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '[object HTMLDivElement]' is not a valid selector.`

I suppose, after your commit https://github.com/dollarshaveclub/stickybits/commit/50d47c70e9c032298fd2e1f1f46c0de71c5250aa, you have added this line of code
https://github.com/dollarshaveclub/stickybits/blob/50d47c70e9c032298fd2e1f1f46c0de71c5250aa/src/stickybits.js#L61
and forgot to remove this, or vise versa
https://github.com/dollarshaveclub/stickybits/blob/50d47c70e9c032298fd2e1f1f46c0de71c5250aa/src/stickybits.js#L165

**Comment by DanielRuf** [comment]
Seems so.

**Comment by DanielRuf** [comment]
Please provide a codepen so we can test this.

**Comment by enheit** [comment]
Here is an example hosted by codesandbox: https://codesandbox.io/s/y5k2oo0xx.
I found that this issue exist when `useStickyClasses: true`, otherwise everything works correct.

**Comment by DanielRuf** [comment]
> Here is an example hosted by codesandbox: https://codesandbox.io/s/y5k2oo0xx.
> I found that this issue exist when useStickyClasses: true, otherwise everything works correct.
> 
> P.S. But if I don't use useStickyClasses: true it doesn't work at all. Element does not follow the page while scrolling.

Mh, is this reproducible with normal setups and codepens using the latest version?

**Comment by enheit** [comment]
@DanielRuf, I've created another example by using codepen: https://codepen.io/mahotskyi/pen/vdJGBR. Take a look when you will have a little time.

**Comment by yowainwright** [comment]
@enheit Thank you for catching this!!!
