### ISSUE TITLE
Can't use when body overflow-x: hidden

### ISSUE THREAD

**Issue by thepedroferrari** [dollarshaveclub/stickybits#253]
Is there any way to have body {overflow-x: hidden} with position sticky and stickybits?
What would be your best guess when we need content outside of the user's view?

**Comment by yowainwright** [comment]
Hey @thepedroferrari ! 

- follow this link: https://github.com/w3c/csswg-drafts/issues/865
- You can checkout this [link to a webpage I built](https://content.dollarshaveclub.com/) a few years ago. It uses position sticky in many places and has hidden content via a side nav. 

Hope those links help and provide context.

**Comment by yowainwright** [comment]
@thepedroferrari closing this issue. Thanks for reaching out! 😊

**Comment by jonjohnjohnson** [comment]
Just letting you know, on the site you linked, it doesn't seem to be falling back to use native sticky (on mac/chrome at least), and instead is using fixed, but with a jarring relayout (that doesn't take the height of the 'sticky' element into account) when crossing the 'stuck' boundary. @thepedroferrari I hope you figured out to scroll an element within the body and not the body/html itself.

**Comment by thepedroferrari** [comment]
@jonjohnjohnson I haven't yet tbh. On my page there is something else going on and I haven't had the time to debug and find what it is. On some pages I testes with overflow-x: hidden + another element sticky, and it indeed works; So it is something on my end I still have to find out.

Thanks for the heads up!

**Comment by dashifen** [comment]
For what it's worth, I also just ran into this.  Once I removed the overflow-x: hidden, the sticky element scrolled as expected; with the overflow-x rule in place, no sticky.  I tried to re-create in a jsfiddle, but no dice.  It always worked there regardless of what CSS I was using so as @thepedroferrari said, it's something more complicated.

**Comment by jonjohnjohnson** [comment]
In how browsers treat internal scrolling elements different than how they scroll the document/html/body, implementations have become looser in allowing `overflow-x: hidden` on html/body tags that will still allow a sticky positioned element to the "scrollingElement". It's unintuitive surely, yet still definitive, and the discussion in https://github.com/w3c/csswg-drafts/issues/865 covers the reasons for the behavior. Note, impending `overflow: clip` will solve this for future browser versions.

**Comment by jonjohnjohnson** [comment]
I'd definitely suggest using `transform` not only for perf not causing reflow with `width` manipulation, but also for `transform` replacing the initial containing block for sticky position to reference internally. And as far as browser support go, I can usually make a nice "fallback" progressively enhancing with @support rules. For fun, check this thing that just uses scrolling to "open" a sidebar (works best in safaris) -> http://jsbin.com/xirowix/edit
