### ISSUE TITLE
Change options

### ISSUE THREAD

**Issue by strarsis** [dollarshaveclub/stickybits#254]
It would be nice if there is a method for changing options after stickybits has been constructed/initialized.
Especially the `stickyBitStickyOffset` option needs changing sometimes.

**Comment by yowainwright** [comment]
Could you explain the feature?

**Comment by strarsis** [comment]
@yowainwright: `MutationObserver` on a header element, when header element height changes (e.g. by media query but also by user/script or anything else), the sticky scroll offset is corrected.

**Comment by yowainwright** [comment]
@strarsis are you planning on working on this feature?

**Comment by strarsis** [comment]
@yowainwright: No.
