### ISSUE TITLE
Different parent

### ISSUE THREAD

**Issue by strarsis** [dollarshaveclub/stickybits#258]
The native `sticky` behaviour constraints the element to dimensions of its direct parent element.
This can be an issue sometimes, in this case the stickied 
element should use the `body` element itself as parent.

**Comment by DanielRuf** [comment]
I do not fully understand your issue. You can use the `scrollEl`.

**Comment by strarsis** [comment]
```js
    stickybits('.sticky', {
      useStickyClasses: true,
      stickyBitStickyOffset: stickyOffset,
      scrollEl: '.main',
    });
````
The element is stickied, but still constrained by dimensions of its direct parent.

**Comment by DanielRuf** [comment]
Please provide a codepen so we can directly see and test this.

**Comment by strarsis** [comment]
@DanielRuf: https://codepen.io/strarsis/pen/MVgeKm

**Comment by strarsis** [comment]
Upon further inspection I notice that apparently just `position: sticky` is applied to it (on Chrome) but no further toggling (like `position: fixed`) for a different scroll element.

**Comment by DanielRuf** [comment]
`position: sticky` is what is used in browsers that support it so this is right.

**Comment by strarsis** [comment]
@DanielRuf: But doesn't this library state it is not a polyfill and that it thereby offers additional, different behaviour?

**Comment by yowainwright** [comment]
Is there an update and/or fix that needed to made @strarsis? If so, please submit a pull request—with a readme or code update. If the update/fix makes sense, I will happily support it being merged. 

Thanks! ~Jeff 🙏
