### ISSUE TITLE
Add support to force using the polyfill's solution, not the native 'position: sticky'

### ISSUE THREAD

**Issue by goldenyz** [dollarshaveclub/stickybits#268]
Although some browser(like Chrome) support the 'position: sticky' natively. But it has bugs in certain cases.
Could you provide a way to force using the polyfill's solution for sticky?

**Comment by yowainwright** [comment]
@goldenyz thanks for reaching out. Stickybits will use `position: sticky` if possible. Note, Stickybits is not a polyfill. It is a utility plugin providing a feature that is often desired on web pages. 

~Thanks

**Comment by goldenyz** [comment]
@yowainwright Thanks for you explanation. What I suggest is to force Stickybits not using the `position: sticky` even the browser support it.

**Comment by yowainwright** [comment]
No

—Thanks for further clarifying. 😁

**Comment by dotKev** [comment]
@yowainwright I need a way to use the inline style/css class solution in Chrome as well. [This bug](https://bugs.chromium.org/p/chromium/issues/detail?id=834054) is affecting me in Chrome.

I understand that _Stickybits is not a polyfill_. If it were a polyfill, I'd expect to use the default functionality if it's available, and fall back to something else for other browsers. As you said, _It is a utility plugin providing a feature that is often desired on web pages_, and that's exactly what I want for Chrome. 😁

Sincerely, thanks for your hard work on this excellent, lean plugin.

**Comment by yowainwright** [comment]
@dotKev noted. I'll add an option asap.

**Comment by yowainwright** [comment]
@dotKev @goldenyz ...just need to write some more tests.

**Comment by yowainwright** [comment]
@dotKev sorry, I forgot. I'll try to get this done in the next few days.

**Comment by yowainwright** [comment]
@dotKev published `3.3.5`.

**Comment by yowainwright** [comment]
I'll probably be supporting issues that are going to pop up no around `position: fixed`. I could use some help. 🙏
