### ISSUE TITLE
Click causes window to scroll to the top

### ISSUE THREAD

**Issue by george-norris-salesforce** [dollarshaveclub/stickybits#272]
Having issue where clicking a button in the sticky nav is causing the window to scroll up. 
Here is the problem recreated https://codesandbox.io/s/4w4kxyxvq7

**Comment by yowainwright** [comment]
@george-norris-salesforce, thanks for sharing! 

I will look.

----

I have seen [a similar problem before](https://www.google.com/search?q=position+sticky+just+on+button+click&oq=position+sticky+just+on+button+click&aqs=chrome..69i57.13612j1j7&sourceid=chrome&ie=UTF-8) with fixed/sticky things. I'm not sure it is the same thing but I am curious. I think #100 may help but it may still require extra work. 

----

If you're in a time crunch, would you be able to use a link?

**Comment by george-norris-salesforce** [comment]
Thanks @yowainwright .. Going to handroll a solution for the moment and check the solutions you mentioned ater. Funny, we just tested this in Safari and it works ok. This is just happening in Chrome.

**Comment by yowainwright** [comment]
@george-norris-salesforce if you have time to share your findings/solution—I'd really appreciate it!

**Comment by george-norris-salesforce** [comment]
Looks like this is a focus() bug. When you click the popover, interally it calls focus() on the popover to capture focus for accessibility. Looks like it is browser bug (?) and doesn't know the sticky element is already in view, and erroneously scrolls to the top of the page. Still digging, but so far is seems that may be what's going on..

**Comment by yowainwright** [comment]
@george-norris-salesforce okay, The link I shared [above](https://www.google.com/search?q=position+sticky+just+on+button+click&oq=position+sticky+just+on+button+click&aqs=chrome..69i57.13612j1j7&sourceid=chrome&ie=UTF-8) **IS** the right google. 😊 

I don't think that stickybits should/can manage this...but I have worked around this issue before. Maybe I can write a little utility? At worst, I think I may be able to find some jQuery I've written for this sort of thing.

**Comment by george-norris-salesforce** [comment]
I ended up writing a little class that made the top nav fixed at a certain point, and used stickybits for the rest. Works pretty well. Thanks for the great library!
