### ISSUE TITLE
Behavior when sticky element is taller than viewport height

### ISSUE THREAD

**Issue by atomiks** [dollarshaveclub/stickybits#284]
Is there a solution for when a sticky element exceeds the viewport in height?

It will be cut off while scrolling until it reaches the bottom of the parent.

https://codepen.io/anon/pen/aGoBVR

See the sidebar here for desired behavior (decrease window height if needed): https://flatpickr.js.org/options

- When scrolling **down**, the element uses `bottom: {offset}` sticky behavior so that the content at the bottom is reachable while scrolling down
- When scrolling **up**, the element uses `top: {offset}` sticky behavior so that content at the top is reachable while scrolling up

**Comment by yowainwright** [comment]
Hey, @atomiks! 

I've never thought of this problem. What are your thoughts? 

...I will look at the codepen later. 
![todoist](https://user-images.githubusercontent.com/1074042/38888129-8c897708-422f-11e8-90c5-d2c690d24e5e.jpg)

**Comment by yowainwright** [comment]
@atomiks I appreciate your example! 

Stickybits could be used to address this behavior but does not support it out of the box.

**Comment by atomiks** [comment]
I believe this is one of the most important functionalities to have actually, as there are many cases in which a sticky element will exceed tbhe viewport height.

Facebook has a sticky sidebar with the functionality I described. I believe it's quite tricky to implement though (lots of logic)

**Comment by yowainwright** [comment]
Thanks for your thoughts, @atomiks.

**Comment by yowainwright** [comment]
@atomiks I greatly value your issue and your OSS work! If I were to write a JS utility with the feature you pointed out, I would write the utility completely differently than how Stickybits is written. 

Maybe it could be another utility UI module?! 😍

I'm closing this issue for now.—Thanks, @atomiks @AsafAgranat!

**Comment by JinHengyu** [comment]
i dont think it can be done with css only
