### ISSUE TITLE
Angular stickybits directive doesn't seem to work with column header.

### ISSUE THREAD

**Issue by kal93** [dollarshaveclub/stickybits#291]
I'm using the stickybits directive for having sticky coulmn header in MatTable. The stickybits works with other things except for the column header.

 [Stackblitz ](https://stackblitz.com/edit/mat-table-stickybits-column-header)

**Comment by DanielRuf** [comment]
Can you provide a codepen so we can see a live demonstration of the issue?

**Comment by kal93** [comment]
@DanielRuf I've provided the stackblitz link. To be more specific in that, the directive is being applied at `line 23` & `line 25` in `table.component.html` .

**Comment by yowainwright** [comment]
@kal93, I only looked at the issue briefly. 

I think this is a documented issue with `<table>` related elements. #143

**Comment by kal93** [comment]
@yowainwright  Thanks for pointing to #143. I was facing similar issue of header getting detached from the table while trying to implement workarounds. Will look more into it.

The directive didn't work only for the column header.
```
This doesn't work.
 <mat-header-cell appStickyBits *matHeaderCellDef mat-sort-header [disabled]="column.disableSorting">
                    <!--For displaying the column label & Icon-->
                    <div class="column-header-content">
                        <span> {{column.displayName}}</span>
                        <mat-icon *ngIf="column.icon" class="icon-align">{{column.icon}}</mat-icon>
                    </div>
                </mat-header-cell>
```
It works fine for the divs & other elements across browsers.
```
This works.
<h4 appStickyBits>Sticky Text</h4>
````

**Comment by ml010979** [comment]
Is there any worka-around?
