### ISSUE TITLE
Non absolute container doesn't work

### ISSUE THREAD

**Issue by Serpentsoft** [dollarshaveclub/stickybits#292]
Hi guys,

Thanks for your great project, But I cannot use it in a real complicated bootstrap 4.1 project, I tried a lot to make it works but I noticed that all examples you provide depending on an absolute .main container which is impossible to use in a real project at least for me.

Any solution for that? 

Best

**Comment by yowainwright** [comment]
Hey @Serpentsoft, 
Thanks for your question. 
The main container definitely does not have to be `position: absolute`. 

Could you provide me a Codepen or code snippet of what you're working with and we can _hopefully_ hack some awesomeness up?

**Comment by Serpentsoft** [comment]
Hi Pal,

Actually it drive me crazy, I cannot make it work in a real project with a lot of nested DIVs or whatever the reason although the new properties wrote correctly {position: sticky; top: 0;}, Anyway It works in a small Fiddle project BUT not when the Main Sidebar larger than the content.

I'm using it side by side with theiaStickySidebar to stick share buttons inside the article content and it works fine in the Fiddle project but in case the main sidebar be larger than the main content and scroll down to the end and go up again it disappears and sticky at the top.

This is the [Fiddle Test Project](https://jsfiddle.net/Oxibug/npqd85hb/) .. Just change the class [**.height-sidebar**] to [2000px] and it'll work fine.

But I'm still trying to make it work even like the Fiddle in my real project.

Thanks for your great project,

Best

**Comment by yowainwright** [comment]
Cool, @Serpentsoft. Let me know when you have that fiddle.

**Comment by Serpentsoft** [comment]
Do you have any ıdea about the heıght dıfference ıssue?? 

Thanks and 'll try to make my issue in the Fiddle.

Best

**Comment by yowainwright** [comment]
@Serpentsoft I'm a bit confused on the problem. In your original fiddle, I saw the social icons become sticky as expected. What do I have to do to replicate the issue you're seeing? ~Thanks

**Comment by Serpentsoft** [comment]
Just continue scrolling to the end of the page then go up again you'll notice that the sticky social area go to top 0.

Best

**Comment by yowainwright** [comment]
@Serpentsoft that document has a lot of HTML. I don't think I'm going to be able to help you as much as I'd hoped. ~Sorry

**Comment by Serpentsoft** [comment]
Yes I thought you need html to be like a real project, I removed all unused, If you want to test it again [The Fiddle](https://jsfiddle.net/Oxibug/8bsu8qpe)

Thanks for your time and your great project.

Best

**Comment by yowainwright** [comment]
@Serpentsoft that was on me about the really project—sorry. Sorry for the late response too. 

From my quick understanding, there is an issue with: https://cdn.jsdelivr.net/npm/theia-sticky-sidebar@1.7.0/dist/theia-sticky-sidebar.min.js.

**Comment by yowainwright** [comment]
@Serpentsoft I'm closing this issue because it relates to a project—not Stickybits. 

Feel free to reach out, though.
