### ISSUE TITLE
About stickybits and breakpoints

### ISSUE THREAD

**Issue by hacknug** [dollarshaveclub/stickybits#30]
Is there any way to disable/enable the plugin under/over a certain breakpoint? I only need my columns to be sticky when they're sitting side by side and not collapsed on top of each other.

Right now I'm using a couple of `!important` to override the plugin inline styles but ideally it shouldn't add them when I don't need it to do nothing,

**Comment by yowainwright** [comment]
I will work working on this asap (next few days) thanks for your thoughtful description @hacknug! 🙏

**Comment by yowainwright** [comment]
@hacknug I'll be addressing this issue with #23 ~Thanks again
