### ISSUE TITLE
Multiple instances of the same selector

### ISSUE THREAD

**Issue by psntr** [dollarshaveclub/stickybits#300]
Hi,

first of all thank you for that simple plugin! I'm just having an issue where I have multiple instances of sticky element inside the same parent container. 

I have enable the `parentClass` options, thus that container has repeat as much sticky element as for parentClass.

Any options allow only one Class for the whole sticky elements?

**Comment by yowainwright** [comment]
Could you provide a Codepen?

**Comment by psntr** [comment]
Sure, I compiled here on jsFiddle:
[code](https://jsfiddle.net/psntrtr/6kqp2znm/1/)
as you can see the parent of the sticky should only have the parent's class once as the sticky elements are the same. But here it repeats many times.

**Comment by yowainwright** [comment]
@psntr Is your intention that the Stickybits items stick to each other or stop before the next one starts?

**Comment by psntr** [comment]
Sorry late reply. The behaviour on the jsFiddle is right. That's what I expect it to do. But what I want to avoid is to have the ".js-stickybit-parent" to be repeated that many times. This class should appears only once. If you inspect the section element (parent of the sticky's elements) you will see that the class appears many times.

**Comment by yowainwright** [comment]
Okay, thanks for clarifying. Stickybits is expecting something like this:
```html
<section>
<article>
 <header class="sticky">This is sticky</header>
  <p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
  </p>
</article>
...
</section>
```

**Comment by psntr** [comment]
I see that makes pretty sense. And it seems to work that way too. 

Thank you @yowainwright !
