### ISSUE TITLE
does customVerticalPosition do anything?

### ISSUE THREAD

**Issue by puglyfe** [dollarshaveclub/stickybits#308]
I'm looking for the best option to stick something in the center of the viewport. Per https://github.com/dollarshaveclub/stickybits/issues/82, something like that _should_ be achievable with `customVerticalPosition`.

However in digging through the source, there seems to be no mention of that option as a Boolean (per the docs) or otherwise. Does it actually exist?

Secondly, this is an amazing library. Thanks for making it 👍

**Comment by puglyfe** [comment]
FWIW, I figured out a solution for my case using `calc()` functions, but the original question still stands.

**Comment by yowainwright** [comment]
You're right @puglyfe. There is an artifact in the readme. Would you like to update that? 

It should be `verticalPosition: 'bottom'`. I didn't update the jquery portion of the readme.

**Comment by yowainwright** [comment]
@puglyfe thanks for the note!

**Comment by puglyfe** [comment]
@yowainwright no problem. thanks for the quick response. sorry i didnt get to the PR. ill put a codepen together to demo center positioning in case others end up here.

**Comment by puglyfe** [comment]
Here's a quick demo to show vertical centering of a sticky child using `calc()` functions - https://codepen.io/puglyfe/full/gKaJQb/
