### ISSUE TITLE
Sticky el mouse events moving with page while sticky el still visibly stuck (Chrome)

### ISSUE THREAD

**Issue by olicarter** [dollarshaveclub/stickybits#318]
On Blisk 9.0.177.201, mouse events aren't detected on the sticky element after scrolling past the point that the element begins to stick. It responds to mouse events as though the sticky element is still scrolling, though visibly, it is stuck to the window as it should be.

If I drag the mouse to highlight text over the sticky element then it "refreshes" and accepts mouse interactions at it's current position, but the issue continues when scrolling again.

Also, if one of the input children of the sticky element is focused before scrolling, mouse events work. Once it loses focus, the issue comes back.

I've tried to replicate this on jsbin with no luck.

**Comment by yowainwright** [comment]
@olicarter this issue is not clear to me. I'm going to need a jsbin or a url.

**Comment by olicarter** [comment]
Looks like it was a temporary glitch. Seems to be working just fine now!
