### ISSUE TITLE
jQuery instance not return

### ISSUE THREAD

**Issue by YuseiUeno** [dollarshaveclub/stickybits#328]
```js
var instance = $('sticky').stickybit();
```
then, `instance` is `undefined`

![image](https://user-images.githubusercontent.com/13248742/41530348-e4094ffe-732a-11e8-8756-8369069fd5ab.png)

I can't do that :( https://github.com/dollarshaveclub/stickybits#jquery-and-zepto-usage

> With `.update`
```js
var instance = $('selector').stickybits();
instance.update();
```

**Comment by DanielRuf** [comment]
Did you include the right file?

https://github.com/dollarshaveclub/stickybits/tree/master/dist

Can you provide us the link to the codepen?

**Comment by DanielRuf** [comment]
Also see https://github.com/dollarshaveclub/stickybits/blob/master/src/jquery.stickybits.js

**Comment by YuseiUeno** [comment]
I just click this link and I store and alert the instance.
[As a jQuery or Zepto Plugin](http://codepen.io/yowainwright/pen/57b852e88a644e9d919f843dc7b3b5f1)

**Comment by YuseiUeno** [comment]
I think do this
https://github.com/dollarshaveclub/stickybits/pull/329

**Comment by DanielRuf** [comment]
> I just click this link and I store and alert the instance.

Can you provide your (forked) codepen?

**Comment by YuseiUeno** [comment]
ok! Please check this.
https://codepen.io/yuseiueno/pen/RJjOEp
