### ISSUE TITLE
How does StickyBits check if the browser supports position: sticky?

### ISSUE THREAD

**Issue by jdengsc** [dollarshaveclub/stickybits#35]
Hi!

I'm evaluating StickyBits for use in the (React) app I'm developing, and it's important to me that the library exits (i.e. doesn't attach an event listener) if the browser supports position: sticky.

I tried looking at the source code and couldn't find any check for the browser support.

Please let me know if this isn't the right place to post this.

**Comment by yowainwright** [comment]
@jdengsc this is a fine place. 🤓 Stickybits checks to see if `sticky` is supported by looping over an array of browser prefixes for `sticky` and seeing if an element adds an inline `sticky` style.

https://github.com/dollarshaveclub/stickybits/blob/master/src/stickybits.js#L6

https://github.com/dollarshaveclub/stickybits/blob/master/src/stickybits.js#L44

If `position: sticky` is supported, then no event listener has to be added.

**Comment by jdengsc** [comment]
@yowainwright Thanks for the quick support and the link!  The code makes a lot of sense to me- I'd prefer to use browser supported `position: sticky` if available and don't want to add too much bloat to support stickiness on older browsers

**Comment by jdengsc** [comment]
Since my question was answered, I am closing this issue.  Thanks!
