### ISSUE TITLE
StickyBit website demo broken on IE11

### ISSUE THREAD

**Issue by darekkay** [dollarshaveclub/stickybits#356]
The [StickyBit Demo](https://dollarshaveclub.github.io/stickybits/) does not render in IE11:

![image](https://user-images.githubusercontent.com/3101914/44523081-f5b18a00-a6d8-11e8-8312-2a948ee7ec70.png)

It's not a layout issue, the items are not rendered at all. This is probably caused by a missing/misconfigured babel transformation, as a console error is thrown:

![image](https://user-images.githubusercontent.com/3101914/44523159-390bf880-a6d9-11e8-8143-52f2ed1053e8.png)

**OS**: Windows 7
**Browser**: IE 11.0.9600.19080CO

**Comment by yowainwright** [comment]
Dammit. 😑 

@darekkay, Thanks for point this out! I'll fix it ASAP.

**Comment by yowainwright** [comment]
@mezoistvan I am confused by your comment. The issue in #289 is an issue with Stickybits. 

The issue here is an issue with `app.js` on the landing page.

**Comment by yowainwright** [comment]
This specific issue was fixed in the `gh-pages` branch. 

This issue pointed out a very interesting bug having to do with css calculation vs offsetTop. I am fixing that one shortly. 

Thank you!

**Comment by mezoistvan** [comment]
@yowainwright Thanks for the response, I opened a separate issue for that problem: #369
