### ISSUE TITLE
window.scrollY is not defined in IE11

### ISSUE THREAD

**Issue by meltuhamy** [dollarshaveclub/stickybits#37]
This plugin doesn't work on IE11 because [window.scrollY is not supported](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY#Browser_compatibility).

**Comment by yowainwright** [comment]
Great catch—thank you!. I'll change this asap. 🙏

**Comment by yowainwright** [comment]
For my [reference](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY#Notes)
