### ISSUE TITLE
Element is not sticky (IE11)

### ISSUE THREAD

**Issue by Oliver-Piorun** [dollarshaveclub/stickybits#374]
Hi!

I am currently using stickybits (3.5.3) in an Angular app to provide a sticky-functionality for IE11.

The element does not get any position attribute in IE11 although it is recognized properly (I checked the return value of stickybits([...]). The position attribute is set in Firefox/Chrome. Do you have any clue what might be going on?

Greetings!

**Comment by yowainwright** [comment]
Hey @Oliver-Piorun, 

I could use more context—link, CodePen, code snippet, pictures, etc. 

Also there is some information setting up Stickybits in Angular [here](https://github.com/dollarshaveclub/stickybits/wiki/Angular-Setup) thanks to @AsafAgranat. Maybe it will help.

**Comment by yowainwright** [comment]
Closing b/c of inactivity. 😄

**Comment by Oliver-Piorun** [comment]
Thanks for replying. Providing more context was not possible due to legal aspects of the project. I switched to Stickyfill.

Greetings!
