### ISSUE TITLE
Angular Example Not Working in IE11

### ISSUE THREAD

**Issue by tuckergordon** [dollarshaveclub/stickybits#390]
This example is linked to in the [Angular Setup](https://github.com/dollarshaveclub/stickybits/wiki/Angular-Setup) page but it does not work correctly for me in IE 11.0.75:

https://stackblitz.com/edit/angular-stickybits-directive

Please see attached screenshots. The header seems to stick but in the wrong place and when its parent element scrolls off screen it then jumps down the page and changes color.

I'm also posting this because I'm trying to use Stickybits in an Angular app and have thus far been unable to get elements to stick in IE11.

![image](https://user-images.githubusercontent.com/7843139/45967120-fd778d80-bffa-11e8-8d7f-611a24016ec5.png)
![pasted_image_at_2018-09-24__1_06_pm](https://user-images.githubusercontent.com/7843139/45967124-ff415100-bffa-11e8-8f39-89d6464a7c1e.png)
![image 1](https://user-images.githubusercontent.com/7843139/45967125-010b1480-bffb-11e8-975d-023efc9dd6e8.png)

**Comment by yowainwright** [comment]
Hey, @tuckergordon! 

**Note:** Stickybits support for Angular is not maintained by people who work on Stickybits. 😃 

Looking at the Wiki Angular example, it is not using the latest version of Stickybits. Could you update the Wiki with a working example?

**Comment by tuckergordon** [comment]
I have yet to be able to produce a working example :sob: but if I get one working I will update the wiki!

**Comment by yowainwright** [comment]
I bumped the version of Stickybits used in the wiki. Hope it helps.
