### ISSUE TITLE
Proposed breaking changes for the next major version

### ISSUE THREAD

**Issue by alexey-m-ukolov** [dollarshaveclub/stickybits#405]
1. Methods should be specifically marked as public or private in the docs. It will tighten library contract and allow to refactor internal bits more freely.

2. Methods should not return `item` when it passed as a parameter to them. Since objects are passed by reference, item outside the method will be changed even without return. It might be confusing to somebody who will think that if they not reassigned item returned from the method their original object was not changed. Only use cases for this that I can see is function composition, but there is not room for it in the library.

3. Property `els` should be turned into local variable. If library user wants to have all elements as a node list, they can just get it first and pass it to library, not use it as a DOM manipulation library.

4. Helper functions should not be exposed. Purpose of this library is to provide sticky polyfill, not to provide `getClosestParent` or `toggleClasses` functionality.

5. I suggest getting rid of `userAgent` property. Since library has no custom logic figuring userAgent out, it offers no additional value to somebody who is debugging it. It's just a dead weight.

All above is just my opinion of course, you are free to disagree and offer additional insight :)

**Comment by yowainwright** [comment]
- **Point (2):** There might be something there. 
- **Point (3):** I would need to look closely at that `els`.
- **Point (1, 5):** The API was more private. Making everything public was specific to vocal customers; same with providing  `userAgent` for debugging. 

----

⚠️ Please use the Github templates.

**Comment by alexey-m-ukolov** [comment]
> do you want to submit a PR for item 2 and close this issue?

Are _you_ ready for the new major release? If so, I can give it a shot next weekend.


> Also, did you receive my email?

Yes, and replied :)
