### ISSUE TITLE
Proposed Updating Props in the Update function

### ISSUE THREAD

**Issue by DarioVaccaro** [dollarshaveclub/stickybits#412]
## Requested Update
Allow for the acceptance of properties as parameters that can be updated when the update function is called.

## Why Is This Update Needed?
For example, when a property is set dynamically based off of a calculation, this property can then change when the update function is called; Could be used when the window is resized and a calculation based off of a page element changes.

### stickybits.js
```javascript
_proto.update = function update(propsToUpdate) {
  for (var i = 0; i < this.instances.length; i += 1) {
    var instance = this.instances[i];
      this.computeScrollOffsets(instance);
        if (!!propsToUpdate) {
          for(i = 0, l = propsToUpdate.length; i < l; i++) {
            instance.props[propsToUpdate[i].prop] = propsToUpdate[i].value;
          }
        }
      }
      return this;
    };
```

### Implementation
```javascript
var stickyHeader = stickybits('#header' , {useStickyClasses: true , stickyBitStickyOffset: -$('#menu-bar').outerHeight() });

window.addEventListener('resize', () => {
  stickyHeader.update([{prop: 'stickyBitStickyOffset', value: -$('#menu-bar').outerHeight() }]);
});
```

**Comment by yowainwright** [comment]
@DarioVaccaro this was discussed before. This looks like it could be a clean enhancement. 

Would you mind submitting a pr with some tests and readme updates?

Let me know how I can help.

Thanks again, 

Jeff

**Comment by DarioVaccaro** [comment]
@yowainwright Sure, I'll write some tests and submit a PR this week. Thanks.

**Comment by yowainwright** [comment]
@DarioVaccaro sound awesome! 

Thank you!!!

**Comment by riiccardo** [comment]
not working for me

just update the value in console log


`props` or `prop` ?

**Comment by riiccardo** [comment]
you don't mentioned
`update` props in website doc I don't see that 

sry
