### ISSUE TITLE
sticky classes applied incorrectly after parent height changes

### ISSUE THREAD

**Issue by kfedorov91** [dollarshaveclub/stickybits#413]
## Requested Update

It seems like stickybits caches some values upon initialization but those cached values become invalid if certain things on the page change, like the height of the parent of the stickied element. Stickybits should be able to detect such changes and re-compute these values automatically, otherwise its calculations are off and it applies sticky classes at the wrong times.

Here's a simple example codepen that shows the issue: https://codepen.io/kfedorov91/pen/rqqYer
Reproduction steps are inside the codepen.

## Why Is This Update Needed?

It's unexpected that sticky classes break if the parent height changes, this broken behavior should at least be documented but ideally fixed.

**Comment by yowainwright** [comment]
@kfedorov91 did you try [`.update()`](https://github.com/dollarshaveclub/stickybits#stickybits-update)?

**Comment by yowainwright** [comment]
Closing b/c the was no response.
