### ISSUE TITLE
Unstick on mobile size

### ISSUE THREAD

**Issue by levipadre** [dollarshaveclub/stickybits#417]
Thanks for the plugin. It's really good so far. It's hard to find a good sticky plugin nowadays.

I created some data attributes to make it easy to use, especially when needs to define offset values for multiple instances (you will see in the example code). This one is working well at the moment.

My problem is when I switch to mobile and want to turn sticky off with cleanup. It says "cleanup is not a function"

Here is the example code: https://codepen.io/levipadre/pen/bQeyag

Any advice or idea?
Thanks!

**Comment by yowainwright** [comment]
Hey @levipadre!  

There are demos of this from previous issues. I can help more (if needed) in about a week. I'm not around much tech right now. 

Thanks!

**Comment by yowainwright** [comment]
@levipadre sorry for the time it took to respond. [Here's]() a thread that will hopefully help

#355
