### ISSUE TITLE
js-is-sticky class added when item not stuck

### ISSUE THREAD

**Issue by DavidChouinard** [dollarshaveclub/stickybits#441]
See this codepen: https://codepen.io/DavidChouinard/pen/ebxrGG

![sticky](https://user-images.githubusercontent.com/388552/51159149-8d587600-183c-11e9-8e8a-7422cb9c9734.gif)

I expect `js-is-sticky` to only be added when the item has reached the top of the screen — when it's "stuck". It appears the class is added anytime the viewport is partially scrolled, regardless of whether the sticky item has reached the top — is this is a bug?

(appears similar to issue #95)

**Comment by yowainwright** [comment]
I made minor tweaks to html in this forked [codepen](https://codepen.io/yowainwright/pen/OrdozP). 

Hope it helps.

**Comment by DavidChouinard** [comment]
Sorry, here's a better test case: https://codepen.io/DavidChouinard/pen/ebxrGG

![sticky](https://user-images.githubusercontent.com/388552/51197579-d218f700-18a6-11e9-9c9e-1764478345ca.gif)

Header #1 behaves as expected, but notice how Header #2 triggers its stuck state midway through the page. How can I detect when Header #2 has reached the top?

**Comment by DavidChouinard** [comment]
Never mind, looks like the `header`/`article` combo need to be enclosed in a div for things to work. Thanks for you help @yowainwright!

**Comment by yowainwright** [comment]
@DavidChouinard, 

Stickybits _should_ work with the dom tree that you had setup if/after [this feature](https://github.com/dollarshaveclub/stickybits/issues/327) is implemented—or by using the `useFixed` option (which won't perform as well in mobile safari). 

----

Stickybits is most useful for "doing stuff" when it **is** sticky. 

In my own UI discussions, I **always** suggest to only use `position: sticky` (no JS and not Stickybits). With the amount of browser support, I find the progressive enhancement approach of using only using `position: sticky` provides for a good experience in older browsers and a great experience most browsers...and all customers win b/c there is 1 less complex thing to worry about. 

----

Thanks for your thoughtful issue and debugging.

**Comment by DavidChouinard** [comment]
Got it, thank you — will follow #327 for a resolution.
