### ISSUE TITLE
Using a sticky header inside of positioned elements

### ISSUE THREAD

**Issue by nickjg231** [dollarshaveclub/stickybits#443]
See this codepen: https://codepen.io/anon/pen/EGJyMK

At the top I have a fixed header of `75px` which needs to remain at the top of the screen, thus I need to use `stickyBitStickyOffset: 75` on my table to account for this. Below the header, I have a very wide table which extends off the screen, so I created an element `.fader`, whose pseudo `::after` element contains a linear-gradient background to show the table can be scrolled horizontally (this is ultimately to appear on mobile). To do this, the `::after` element needs to have `position: absolute`, which means the `.fader` element needs `position: relative`. The table which uses the sticky header is a descendant of the `.fader` element, meaning it's positioned by an element instead of by `window`. This seems to cause a problem with Stickybits, as the table header is offset relative to the `.fader` element, and the header does not seem to stick when scrolled below the table. 

I have searched through closed issues and have not found anything similar to this problem. Is there a way to work around this? I'm pretty confident this is an issue with the `.fader` element, since removing it from my example makes the table header stick. I've tried the `scrollEl` option but I do not believe this option applies to my scenario. The `useFixed` option is something I've been attempting to use as well, but this option also doesn't seem to allow the header to stick above the content when scrolling. 

Is it possible to have a positioned element between the table and window and still allow the table header to stick?

**Comment by yowainwright** [comment]
Hello @nickjg231:

Using `position: sticky` within table elements is a [documented issue](https://github.com/dollarshaveclub/stickybits/issues/143) outside of using Stickybits.

If you could submit a similar Codepen but using divs, that would be great! I'll work with you on that CopePen (although, this is a chance that switching to divs will fix your issue 😊).

**Comment by nickjg231** [comment]
Thanks for the response @yowainwright. Here is an updated codepen using all divs: https://codepen.io/anon/pen/KJPJKJ

Unfortunately, switching to divs did not seem solve the issue. I believe it may still be due to the relatively positioned `.fader` element, but I'm not certain. I've tried using both `.table-header` and `.table-header div` as selectors when creating stickybits initially, but with no results. Do you have any ideas?

**Comment by yowainwright** [comment]
@nickjg231 I'll try to look within the next days. I've add a note to my todo list 😊.

**Comment by yowainwright** [comment]
@nickjg231 it has to with the `.scrollable-div`. Here's a forked [codepen](https://codepen.io/yowainwright/pen/Ermdqj) where I removed that element which then doesn't reference those styles. 

...Something will need to be done about that. 

~Thanks. Sorry it took me a bit to respond.
