### ISSUE TITLE
Add option to stick the element to bottom or top depending on scroll direction

### ISSUE THREAD

**Issue by jdolinski1** [dollarshaveclub/stickybits#447]
## Requested Update
Add option to stick the element to bottom or top depending on scroll direction

## Are There Examples Of This Requested Update Elsewhere?
As here: http://leafo.net/sticky-kit/ - example `Scrollable Sticky Element`, the "Very tall sidebar" div is dynamically sticked to top when you scroll bottom, or to bottom if your scroll direction is top.

Thanks.

**Comment by yowainwright** [comment]
Hey @jdolinski1 

This has been discussed in other issues. Here is link to a [demo](https://github.com/dollarshaveclub/stickybits#extended-examples).

~Thanks

**Comment by jdolinski1** [comment]
Hello, you did not provided link to a specific demo, just list of demos. Please advise which one i should focus on.

**Comment by younes0** [comment]
@jakiestfu did you manage for this one?

**Comment by younes0** [comment]
This snippet allows the same behavior found on this page:
https://www.zara.com/fr/fr/mini-jupe-%C3%A0-ceinture-p04886254.html

```js
const stickyEl = document.querySelector('.myStickyEl')
const distanceFromTop = 120 // adjust as you wish
let scrollPos = 0

const setStickElTop = directionIsDown => {
  stickyEl.style.top = directionIsDown
    // allows to scroll to bottom when sticky element is highter than viewport
    ? window.innerHeight - stickyEl.offsetHeight + 'px'
    : distanceFromTop + 'px'
}

// will show upper part of the sticky element when scrolling up
const scrollListener = () => {
  const top = document.body.getBoundingClientRect().top
  setStickElTop(top < scrollPos)
  scrollPos = top
}

window.addEventListener('scroll', scrollListener)
stickybits(stickyEl)
```

Enjoy
