### ISSUE TITLE
Expected behaviour of IE11 handling of tables?

### ISSUE THREAD

**Issue by cayuu** [dollarshaveclub/stickybits#449]
## Requested Update

Hi there, just a question, rather than a request: is stickybits expected to work with IE11 for **tables**, specifically pinning `<thead><th>...` cells? I'm guessing not, having read through a few other tickets and tried a few options, but thought I'd try for a canonical "no" :)

I've set up a JSBin that puts a very basic example in play, that works for almost everything I've tested, except IE11:

https://jsbin.com/qahahoxaka/edit?html,css,js,output

## Why Is This Update Needed?

Would be great to have an approach that works for IE11, even if it's a bit of a hack.

## Are There Examples Of This Requested Update Elsewhere?

#143 is the most related, with Firefox having had the same issue of not supporting sticky for certain table elements.

Thanks in advance!

**Comment by samk-ayyagari** [comment]
+ 1

**Comment by yowainwright** [comment]
Stickybits is not particular to `<table>` elements or browser issues with the `position: sticky` and `position: fixed` on `<table>` elements. 

AKA, no Stickybits js will be added to the utility to support specific elements in specific browsers. 

The quick fix is, don't use `<table>` for `sticky/fixed` items. Or, don't make `<table>` elements  `sticky/fixed`. 😃

~Thanks
