### ISSUE TITLE
How does customStickyChangeNumber work?

### ISSUE THREAD

**Issue by StephenMeehan2016** [dollarshaveclub/stickybits#471]
Stickybits is super useful, many thanks for this!

Could you explain how `customStickyChangeNumber` works? The docs mention this, but other than this sentence there's no other mention?

 > The scroll duration for when .js-is-sticky--change is added can be modified by providing a number for customStickyChangeNumber option.

I'm finding `.js-is-sticky--change` is being added too early and removed too late.

An example would be really helpful.

**Comment by yowainwright** [comment]
@StephenMeehan2016 could you provide a code example with your issue so that I can try and help? ~Thanks
