### ISSUE TITLE
problem when scrollEl is not on the top

### ISSUE THREAD

**Issue by athena0304** [dollarshaveclub/stickybits#474]
## Requested Update
add another option that can calculate the offsetTop of the wrapper of the scrollEl
## Why Is This Update Needed?
when we need to set the scrollEl, probably the scrollEl is not on the top of the view, so mistake happens, just like the following example.
## Are There Examples Of This Requested Update Elsewhere?

https://codepen.io/athena0304/pen/vPWPgJ

> Read about references issues [here](https://help.github.com/articles/closing-issues-using-keywords/). Provide paragraph text responses to each header.

**Comment by athena0304** [comment]
it does not work when using flex

**Comment by yowainwright** [comment]
@athena0304 is the second comment related to the first? ~Thanks
