### ISSUE TITLE
It doesn't work if there is overflow: hidden somewhere on the parent

### ISSUE THREAD

**Issue by SilencerWeb** [dollarshaveclub/stickybits#475]
It doesn't work if there is `overflow: hidden` somewhere on the parent (no matter on what tree level)

**Comment by yowainwright** [comment]
@SilencerWeb Could you provide more detail and an example?

**Comment by SilencerWeb** [comment]
@yowainwright, add `overflow: hidden` to the block with class `content-block__inner`:

![image](https://user-images.githubusercontent.com/20713191/54896286-46929680-4ee5-11e9-9d8d-57ca29ee1e00.png)

Here is the sticky block:

![image](https://user-images.githubusercontent.com/20713191/54896297-53af8580-4ee5-11e9-9365-53340a7c39cb.png)

Link to the website — https://mutify.app/privacy-policy

**Comment by yowainwright** [comment]
@SilencerWeb Thanks for the detail! Sorry it took me a bit to get back to you. 

----

I found this [issue](https://github.com/w3c/csswg-drafts/issues/865). There are a few CSS rules that don't play well together. This appears to be one of them. Stickybits can't support specific CSS issues that exist within browsers. 

Thoughts?

~Thanks again!
