### ISSUE TITLE
IE11 - No 'position:fixed' added on scroll

### ISSUE THREAD

**Issue by esvi** [dollarshaveclub/stickybits#481]
Hi,

I am having trouble getting this to work in IE and Edge. I only see the `js-stickybit-parent` class being added (even in Chrome with `useStickyClasses`).

Never seeing `js-is-sticky` or `js-is-stuck` being added. 
`style="top: 70px;"` is added to the sticky element in IE but never any positioning as in Chrome.

All relatively positioned containers, no weird CSS on any of the elements, no heights, positioning or overflows.

The HTML structure looks something like this:
```
<div id="content"> <!-- CSS: position: relative; width: 100%; -->
   <div class="some-content"></div>
   <div class="js-stickybit"></div>
   <div class="some-more-content"></div>
</div>
```

```
stickybits('.js-stickybit', {
   scrollEl: '#content',
   useStickyClasses: true,
   stickyBitStickyOffset: this.offset // 70
});
```

Am I missing something? Do I have to do anything special to make it work in IE?

Using the latest version at the moment (`v3.6.4`). 

Thanks :)

**Comment by henrythiemann** [comment]
I'm also unable to get this working in IE (although it is working in Edge for me).

I'm seeing the same behavior: `js-stickybit-parent` is added to the parent element, but the sticky element does not have `js-is-sticky` or `js-is-stuck`.

I double checked that no ancestor elements have a non-default `overflow` value.

In the meantime, [stickyfill](https://github.com/wilddeer/stickyfill) is working for me.

**Comment by esvi** [comment]
Thanks [stickyfill](https://github.com/wilddeer/stickyfill) works 100%.

Still can't figure out why this does not -.-
