### ISSUE TITLE
stickybits_1.default is not a function

### ISSUE THREAD

**Issue by aspramsh** [dollarshaveclub/stickybits#486]
I am using Angular 6. I get this error:

error! TypeError: stickybits_1.default is not a function
    at new StickybitsDirective 

I have done exactly as is written in the wiki. My code is exactly the same as here:
https://stackblitz.com/edit/angular-stickybits-directive?file=typings.d.ts

Could someone help me?

**Comment by FrankMerema** [comment]
If it's exact the same this is a very hard issue to help with, can you provide more details about your current setup?

**Comment by FrankMerema** [comment]
Can we close this one due to inactivity?
