### ISSUE TITLE
Failure to stick properly in Chrome on 3rd child

### ISSUE THREAD

**Issue by IanYates** [dollarshaveclub/stickybits#49]
I've copied a fairly simple Codepen demo I found and have embellished it slightly.
Link to my pen: https://codepen.io/IanYates/pen/ZyaQXZ

In latest Chrome (Version 61.0.3135.5 (Official Build) dev (64-bit)) on Windows you can scroll down and get image 1's header behaving properly, and image 2's header behaving properly but image 3's header doesn't stick.

In IE 11 this seems to work properly.

The CodePen I originally sourced from (https://codepen.io/yowainwright/pres/QdedaO) had a slightly older JS version that didn't work in IE 11.  I've updated its JS code to the latest from the dist folder here.  Apart from that change, and adding some more divs and the img elements, everything is the same.

I've tried multiple stickybits calls (targeting a specific div each time) and using a single stickybits call (selector targets all child divs).  No difference.

With only 2 images it seems to behave correctly.

Any thoughts?

Thanks for the library - it came up in my Google news feed and happens to be exactly what I've been looking for :)

**Comment by yowainwright** [comment]
@ianYates, I will dig into the Codepens ASAP! Thanks for your detailed issue! 🙏

**Comment by yowainwright** [comment]
@IanYates there were some minor tweaks I did with the codepen you shared. It appears that stickybits is working correctly and that we just need to modify the `html` and `css` slightly. 🙌 

~Btw, thanks for pointing out that the codepens were out of date. I will update that asap. 

Here's what I forked for your codepen: https://codepen.io/yowainwright/pen/VWrjVw
—Sorry, in advance, if the forked codepen I made is further from your visual goal. 

One last quick note: each Stickybit is sticky relative to its `<parent>. If all Stickybits are in the same `<parent>`, that will be an issue—not just with `stickybits` but with the css prop `position: sticky`. If you want `<elements>` to become sticky within 1 `<parent>` you might want to use `position: fixed` and leverage `window` on scroll to set them to fixed—this method has other problems though.

**Comment by IanYates** [comment]
Hi @yowainwright - thanks so much!

I am looking to have every Stickybit in its parent.  The idea is that I've got a scrolling list of document pages (images) and want a header at the top of each image with some text and a couple of buttons, etc.  Whilst the image is on-screen I want its heading to still be visible even though perhaps the top 50% of the  of image has been scrolled out of view and the next image is partially visible (with its heading at the top of it part of the way down the viewport).

Your updated example seems to support this pretty well.  I'll need to read up more on this to see what the pitfalls are.  If it's just that the Stickybit `<div>` elements pile up at the top and sit underneath each other then I'm OK with that since visually it's still what I'm after.

I can see in Chrome it works amazingly well now.  In IE it's a bit glitchy but I'll look into that more when I get some time later this week.

Thanks again!!

**Comment by yowainwright** [comment]
@IanYates no prob! Thanks for the details. 🙌

I plan on tackling older IEs soonish. Let me know if you want to help w/ it ...?

**Comment by IanYates** [comment]
I don't have access to anything older than IE 11.   (well I have plenty of VMs but we tell our clients we don't support IE < 11)

I imagine IE 10 probably isn't too bad since it's not that different from 11.  For supported Windows versions you only come across IE 10 if someone's running Windows Server 2012, since Windows 7, 8.1, 10 and Servers 2008 R2, 2012 R2 and 2016 all have IE 11 available.   I guess if Windows 8.0 is still in support (??) then it too would be IE 10 only.

I'll keep you posted on anything else I find / fix.
