### ISSUE TITLE
Remove --save-dev from project website

### ISSUE THREAD

**Issue by theiliad** [dollarshaveclub/stickybits#504]
Hi, I couldn't find the source to the website to make a PR for this.

Why would we install this stickybits as a dev dependency?
![image](https://user-images.githubusercontent.com/14989804/57185194-e7855180-6e94-11e9-8887-98e767f7952c.png)

**Comment by FrankMerema** [comment]
The website (I think) is in the gh pages branch of this project. Maybe you can check it out and make a PR?

**Comment by FrankMerema** [comment]
Don't forget to release the new version of the gh pages and the lib ;)

**Comment by yowainwright** [comment]
@FrankMerema of course.

**Comment by FrankMerema** [comment]
When do you expect to do a new deploy to the https://dollarshaveclub.github.io/stickybits/ ?

**Comment by yowainwright** [comment]
@FrankMerema it would be great to integrate that into the build!

**Comment by FrankMerema** [comment]
Can we think of something clever, because its a separated branch now? ( I have never used github pages before :p )

**Comment by DanielRuf** [comment]
Either we can use [`gh-pages`](https://www.npmjs.com/package/gh-pages) or the [`deploy`](https://docs.travis-ci.com/user/deployment/pages/) task of TravisCI for pages.

Or CircleCI as we already use it but it looks a bit more complicated.

https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/

**Comment by theiliad** [comment]
You should use Netlify.

1. Login
2. Add project
3. Enter deploy script
4. Enter publish directory

And done
