### ISSUE TITLE
verticalPosition: 'bottom' broken in IE

### ISSUE THREAD

**Issue by DBjelovuk** [dollarshaveclub/stickybits#524]
The element remains fixed even after scrolling up beyond the top of the parent. Sticky behaviour should be that it stays contained within the parent. Default vertical position seems to work as expected.

**Comment by yowainwright** [comment]
@DBjelovuk Could you provide an actual code sample? ~Thanks

**Comment by yowainwright** [comment]
Closed b/c of no follow-up. ~Thanks
