### ISSUE TITLE
stuckClass not being removed if you scroll too fast

### ISSUE THREAD

**Issue by randyb62366** [dollarshaveclub/stickybits#53]
If the size of the sticky element is not very large it is possible to scroll fast enough that the stuckClass is not removed.

**Comment by yowainwright** [comment]
@randyb62366 Thanks for noting this. Could you share demo or example webpage that illustrates this? 🙏

**Comment by randyb62366** [comment]
I looked at the last check in and it appears that this has been fixed.  I
will let you know if I have any issues after I try it out.

Thanks,
Randy

**Comment by yowainwright** [comment]
@randyb62366 Thanks for the response & feedback! 🙏
