### ISSUE TITLE
IE11 - once height of content is increased on page Stickybits stops being position:fixed after same amount of height

### ISSUE THREAD

**Issue by rynoska** [dollarshaveclub/stickybits#548]
## Are There Examples Of This Requested Update Elsewhere?

> Read about references issues [here](https://help.github.com/articles/closing-issues-using-keywords/). Provide paragraph text responses to each header.

**Comment by macronomicus** [comment]
ugh... ie.......  did you find a solution?

**Comment by rynoska** [comment]
The only solution we came up with was re-adding the script after the user
clicked "load more" which did work as it then recalcuclated the height of
the overall screen size.

**Comment by PradipShrestha** [comment]
Facing similar issue. What do you mean by re adding the script? Please advise. :)

**Comment by rynoska** [comment]
Every time an event happens, for instance clicking on a load more button
that extends the height of the screen, that event would also re-load the
three-ish lines of code that add the position: sticky or position: fixed
style attribute to the delegated class or tag.

Ryne

**Comment by DanielRuf** [comment]
Hi, can you please fill out the issue template?

Mutation observers can not be used in IE, you have to trigger the recalculation.

Normally you can simply destroy and reinitialize stickybits using its API and methods.

**Comment by yowainwright** [comment]
See @DanielRuf's comment and this [link](https://github.com/dollarshaveclub/stickybits#stickybits-update). :pray:
