### ISSUE TITLE
The issues when usesd in ionic project

### ISSUE THREAD

**Issue by Freshfishfish** [dollarshaveclub/stickybits#550]
the sticktbits's class doesn't take effect when the ionic page is scrolling. How to solve,please?

**Comment by ianhobbs** [comment]
what is iconic page?

**Comment by Freshfishfish** [comment]
> what is iconic page?
Ionic page is the web page built on the ionicframework,Please go to https://ionicframework.com/ seeing more!

**Comment by DanielRuf** [comment]
Hi @Freshfishfish,

Can you provide a reproducible testcase using something like StackBlitz?

I guess it is because of some tricks that Ionic does like `position: fixed`.

**Comment by Freshfishfish** [comment]
Hello @DanielRuf ,
I just write a simple example on StackBlitz,see https://stackblitz.com/edit/ionic-np5oqp?file=package.json
Thanks!

**Comment by yowainwright** [comment]
The demo looks to not use Stickybits. It uses `ngx-stickybits`. The maintainers of Stickybits can't help with work they don't maintain. ~Thanks
