### ISSUE TITLE
stickybits not working on IE11

### ISSUE THREAD

**Issue by niralijg** [dollarshaveclub/stickybits#556]
It's not supporting for IE11.
Environment detail: IE11 Browser on windows 7

**Comment by DanielRuf** [comment]
Hi @niralijg,

please provide a codepen which reproduces / demonstrates this issue.
Did you also check the other related issues?

https://github.com/dollarshaveclub/stickybits/issues?q=is%3Aissue+ie11+is%3Aclosed

**Comment by niralijg** [comment]
@DanielRuf : Thanks for replying 👍 

yes i have checked other issues details but couldn't find the proper solution .
stickbits doesn't support on iE11

**Comment by yowainwright** [comment]
No example provided. Closing. ~Thanks
