### ISSUE TITLE
Position: fixed set on a sticky element early if scrollEl is used

### ISSUE THREAD

**Issue by sbadya** [dollarshaveclub/stickybits#583]
Steps to reproduce:
1. Open https://codepen.io/yowainwright/pen/EXzJeb
2. Use force fixed ({useFixed: true})

**Comment by DanielRuf** [comment]
Hi @sbadya,

Can you clarify what the issue is?

**Comment by sbadya** [comment]
Hi. If you open link with the sample, set {useFixed: true}  in stickybits options, then start to scroll element (scrollEl), position fixed on a sticky element set early before as sticky will be on a top scrollEl
