### ISSUE TITLE
Question: Add class with jquery to other element upon stick?

### ISSUE THREAD

**Issue by casbboy** [dollarshaveclub/stickybits#584]
## Requested Update

Is there a way to run another jquery function at time of "stick"? Doing the jquery stickybits.

I want to add a class to another element (with class) every time it sticks and remove when unsticks.

Cheers!
Ryan

**Comment by yowainwright** [comment]
Adding events, which would do what you're suggested, was discussed in detail. It was decided that if there were multiple stickybit items with the same information—same classes, etc, events could become very confusing. 

To solve your issue @casbboy you could 'watch' for a sticky item to have a class and do something. This would be pretty inefficient so I'd recommend not doing it if possible. 😄
