### ISSUE TITLE
How to use it in Hype

### ISSUE THREAD

**Issue by alexlii1971** [dollarshaveclub/stickybits#594]
Hello,

Sorry for put this request under issue tab since I did not find other place, and please close it if you think this make you confused.

I am frontend UI designer, and I use Hype https://tumult.com/ for web page and Animation design.

We usually use external JS/Css resource/library referenced in Hype:

![1572061078732](https://user-images.githubusercontent.com/15896194/67613861-15fd3d00-f7e5-11e9-996d-68a411f05fed.jpg)

and it also support assigning CSS class and Html atrributes to any elements:

![download (1)](https://user-images.githubusercontent.com/15896194/67613927-29f56e80-f7e6-11e9-9d43-a228aef76655.png)

￼I tried as above, but it seems not work, and I just suppose it might need some custom javascript to work as stickybits('selector');

In Hype, it support to run a custom javacript to achieve specific feature:

![Unknown-2](https://user-images.githubusercontent.com/15896194/67613964-f2d38d00-f7e6-11e9-8ded-a2a01e332273.jpg)

**I am trying to make this style working in Hype:

https://codepen.io/yowainwright/pen/EGvjYg**

It would be great appreciated if you could help with a custom javascript to support it or any other suggestions to make stickybits work in Hype.

Here is Hype API for your reference:
https://tumult.com/hype/documentation/#api-functions

Thanks in advance, and have a nice day.

**Comment by yowainwright** [comment]
Sorry, this is not an Hype project. The maintainers of this project can’t help you with Hype. ~Thanks!
