### ISSUE TITLE
Angular example doesn't work with useFixed set to true

### ISSUE THREAD

**Issue by GargantulaKon** [dollarshaveclub/stickybits#599]
## Requested Update

Fix stickybits to work with useFixed set to true when using Angular

## Why Is This Update Needed?

So that more people can use it easily.

## Are There Examples Of This Requested Update Elsewhere?

Not that I know of.

> Read about references issues [here](https://help.github.com/articles/closing-issues-using-keywords/). Provide paragraph text responses to each header.

Here is where I referenced the code and changed the Angular directive to use useFixed: true: https://github.com/dollarshaveclub/stickybits/wiki/Angular-Setup

**Comment by yowainwright** [comment]
Sorry, this is not an Angular project. Feel free to reach out to the wiki author or update the wiki post with your updates. ~Thanks!
