### ISSUE TITLE
IE11 Issue 

### ISSUE THREAD

**Issue by Amulya-sb** [dollarshaveclub/stickybits#621]
I am trying to attach sticky for table body first row .
In Chrome and firefox completely working fine .
For each td position:sticky is appending.
But in IE , lets say am having 10 td , for parent tr 10 times **js-stickybit-parent** class is appending .
So that not working in IE11 !! 
![issue](https://user-images.githubusercontent.com/45749186/70055281-42d01b80-15ff-11ea-8dd4-4bd99c934dd7.PNG)

**Comment by Amulya-sb** [comment]
Not fixed , please can u explain the way .

**Comment by mbark** [comment]
@Amulya-sb the fix for the bug with multiple parents hasn't had a release made yet. You could use the unreleased version by installing explicitly from the github repo.

To do that update your `package.json`:
```json
"stickybits": "git+https://github.com/dollarshaveclub/stickybits.git"
```

**Comment by yowainwright** [comment]
@Amulya-sb there could also be a _slight_ chance that this doesn't work because the `<table>` element is being used.
