### ISSUE TITLE
stickybits element width in IE

### ISSUE THREAD

**Issue by aitboudad** [dollarshaveclub/stickybits#66]
Hi
When position: fixed is applied to the sticky element (in IE) it doesn't preserve it's width see bellow:
![stickybits](https://user-images.githubusercontent.com/1753742/28365194-737173aa-6c7f-11e7-907e-c7c663adc932.gif)

Thanks!

**Comment by yowainwright** [comment]
@aitboudad thanks for the demo! Could you provide a quick Codepen example? I think/hope we can add a little css and make it all better 🙏

**Comment by aitboudad** [comment]
@yowainwright see https://codepen.io/anon/pen/BZgVrz

**Comment by yowainwright** [comment]
@aitboudad https://codepen.io/yowainwright/pen/BZgeWN

```css
max-width: inherit;
width: 100%;
```

I think that is on the right path ...? 

Could you hack at it a bit? 🙏

**Comment by cyr-x** [comment]
@yowainwright That's not fixing it (Tested on IE11, Edge 14 & 15).

Only way i've managed it was applying your fix + `max-width` set on parent.

**Comment by yowainwright** [comment]
@cyr-x awesome! 

Unrelated to @cyr-x's comment—there are probably many ways to solve this issue. Keep 'em coming. 🙌

**Comment by aitboudad** [comment]
it doesn't solve my issue as in my app I use the grid system (parent doesn't have a specific width).
IMO the better approach is to set the width using js.

**Comment by yowainwright** [comment]
@aitboudad if you could post your solution here that would be awesome. 

I DO think this issue is very valuable for Stickybits to have s people can reference their solutions. 

Thanks for sharing!

**Comment by aitboudad** [comment]
just tested with another alternative lib [stickyfill](https://github.com/wilddeer/stickyfill) and  it appear that handle that issue by setting `width` to `auto` and add left + right to the sticky element see https://github.com/wilddeer/stickyfill/blob/master/src/stickyfill.js#L179-L183

**Comment by yowainwright** [comment]
@aitboudad thanks for sharing. Those styles can be added be added with css:

```css
.js-is-sticky[style="postion: fixed"] {
  left: <left val>;
  top: <top val>;
  bottom: <bottom val>;
  width: <width val>;
}
```
The benefit of not assuming what an interface needs (aka **not** `position: sticky` polyfill 🙂 ) is that styles and javascript can be added to create the desired affect. 

If the interface requires the sticky element to be positioned at the bottom or not directly at the top of the browser window (see readme examples) there are a few issues with a full polyfill approach:

1.  The plugin file size is larger for a feature that should _questionably_ just default to `position: static` for non-supported browsers (b/c `position: sticky` has growing support and a `position: static` is **not** broken—users probably wouldn't know or care). 
2.  Along with the plugin's larger file size, the interface is more locked into 1 approach for sticky elements however often the interface requires sticky elements directly **not** to be at the top of the browsers. To achieve that desired affect the developer has to write css or javascript to override the plugin defaults which means **even more code**!

**Comment by aitboudad** [comment]
make sense and I'm totally agree with all arguments, I'll try to find a better approach to my use-cases.
Anyway thanks for all!

**Comment by rosivanov** [comment]
Hi all! For IE when sticky element is `position: fixed` i used
```css
width: 100%
max-width: ...px
```
Looks like workaround however anybody knows better solution?
