### ISSUE TITLE
Perhaps mention that you may need z-index to a high value set in the docs

### ISSUE THREAD

**Issue by kvanberendonck** [dollarshaveclub/stickybits#73]
For some reason I had to use

`z-index: 10; /* in front */`

a lot for the elements I set sticky, even though nothing else on the page had a z-index, otherwise they scrolled behind whatever other things were in the same container. I didn't notice because my element was really skinny, so for a while I just thought they were just stuck in place and nothing was working, heh.

The behavior is different when using native `position: fixed` where I didn't have to set the `z-index`.

**Comment by yowainwright** [comment]
Could I view the webpage you're working on? ...Or codepen where I can view the issue?

**Comment by vihryn** [comment]
@kvanberendonck what browser ? Cause I see similar behavior in Chrome, and don't in Firefox.

**Comment by kvanberendonck** [comment]
@vihryn Firefox, chrome was actually working fine.

Can't reproduce this anymore since I set everything to `display: block` instead of `flex`, so I'll close this and just assume its a browser quirk not a library quirk. People can find this thread on google easily enough.
