### ISSUE TITLE
Re check `stickystart` + `stickystop` values

### ISSUE THREAD

**Issue by donkeybonks** [dollarshaveclub/stickybits#74]
Firefox 54.0.1 (32-bit)
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

Using `{useStickyClasses: true, stickyBitStickyOffset: 0}`.

**Comment by yowainwright** [comment]
Could I view the webpage you're working on? ...Or codepen where I can view the issue?

**Comment by kvanberendonck** [comment]
Here is a plunkr http://plnkr.co/edit/fvTJ0OfYzhZjoei6AIS6

I can't reproduce this right now at home though (OS X). I was having the issue at work (Windows).

**Comment by yowainwright** [comment]
@kvanberendonck if you can let me know, I'd appreciate it. 🙏

**Comment by kvanberendonck** [comment]
OK so I'm not having trouble in the plunkr, but I'm still having trouble in our app, which unfortunately is only hosted internally, so I'll have to debug and try and figure out why ...

The only thing I can think of is that it's within many container elements, and one of them could be messing it up.

**Comment by kvanberendonck** [comment]
In debugging this, I added debugs to `manageState` like so:

```
  this.manageState = function () {
    console.log('scroll', stickyStart, stickyStop, state);
    var scroll = isWin ? se.scrollY || se.pageYOffset : se.scrollTop;
    var notSticky = scroll > stickyStart && scroll < stickyStop && (state === 'default' || state === 'stuck');
    var isSticky = scroll < stickyStart && state === 'sticky';
    var isStuck = scroll > stickyStop && state === 'sticky';
    if (notSticky) {
      state = 'sticky';
      console.log('notSticky1');
      rAF(function () {
        toggleClasses(stuckClass, stickyClass);
        styles.bottom = '';
        styles.position = pv;
        styles[vp] = offset + 'px';
      });
    } else if (isSticky) {
      state = 'default';
      console.log('isSticky1');
      rAF(function () {
        toggleClasses(stickyClass);
        if (pv === 'fixed') styles.position = '';
      });
    } else if (isStuck) {
      state = 'stuck';
      console.log('stuck1');
      rAF(function () {
        toggleClasses(stickyClass, stuckClass);
        if (pv !== 'fixed') return;
        styles.top = '';
        styles.bottom = '0';
        styles.position = 'absolute';
      });
    }
  };
```

The result was that I never got the `notSticky1`, `isSticky1` or `stuck1` debug messages, but got a lot of `scroll` debug messages (so at least the handler is working)`. The readout always reads the same thing over and over:

```
scroll 111 21 default
```

**Comment by kvanberendonck** [comment]
It would appear the issue is that `stickyStop` is not being calculated correctly in my case, for example looking at the values of `parent.offsetHeight`, `el.offsetHeight` and `offset`, I get:
```
poh 0 eloh 90 off 0
```
Which results in `stickyStop < stickyStart`.  🗡

**Comment by yowainwright** [comment]
That means that the `parent` doesn't have a height according to the browser renderer. Is it floated or something? 

**For debugging**: could you try putting the css property: `overflow: hidden`; Or add the [clearfix hack](https://css-tricks.com/snippets/css/clear-fix/) to it...

**Comment by kvanberendonck** [comment]
The parent is a flexbox container, could have something to do with it . I'll let you know in ~45m

**Comment by yowainwright** [comment]
It shouldn't. All of the examples use `display: fiex`. Thanks for digging into this!

**Comment by kvanberendonck** [comment]
OK I was able to resolve this .. it's a combination of 2 things. One will need a bug fix in this library ...

--Issue 1--: my parent element was inheriting `display: flex` from a distance flex parent and this was giving it an offsetHeight of 0 despite `overflow: hidden` making no difference to the page display... When I changed it to `display: block;` all is good now.

--Issue 2--: if you refresh the page while you are scrolled halfway down the page, `stickyStart` is wrong. This was throwing me off a bit ... it'll take a negative value i.e. `-389` instead of a logical value like `100`. I think this is an actual bug in the library ...

**Comment by yowainwright** [comment]
Mmm, issue 2 is an interesting 1. I/we should fix that! 

The issue is that some value is stored outside of the scroll event. We could probably use a ternary to fix that by recheck certain values to see if they've changed. Do you fix that or should I? 

I'm happy to update it—I just don't know if you'd like to do that and then that way you can reference yourself as a contributor if you'd like ...for all of the work you're doing 🤓

**Comment by kvanberendonck** [comment]
I can't really do a PR, it's too complicated with ownership as I'd have to get permission sorry.

**Comment by yowainwright** [comment]
[Fork and PR](https://help.github.com/articles/creating-a-pull-request-from-a-fork/). You don't need permissions.

**Comment by kvanberendonck** [comment]
No I actually mean because of my contract I don't own any of the code I write if it's remotely related to something I've been working on professionally.

**Comment by yowainwright** [comment]
You could do it specifically for you—no one else required for what it's worth ...I will work on an update asap. 🤓

**Comment by yowainwright** [comment]
I haven't been able to replicate this issue. 😑

**Comment by kvanberendonck** [comment]
I'll try make a plunkr for issue 2..

**Comment by yowainwright** [comment]
@kvanberendonck 🙏

**Comment by yowainwright** [comment]
@kvanderendonck https://github.com/dollarshaveclub/stickybits/blob/master/README.md (see the bottom)

**Comment by yowainwright** [comment]
Closing. ~Thanks. I will be following up with this @ #93.
