### ISSUE TITLE
Bottom sticky doesn't update until you scroll onto its parent

### ISSUE THREAD

**Issue by donkeybonks** [dollarshaveclub/stickybits#76]
If you have something above the parent containing the bottom sticky, it doesn't move the bottom sticky into place until the top of the page passes the top of the parent element, and then it jumps into place at the bottom.

Tested on Firefox with bottom sticky settings:
`{useStickyClasses: true, stickyBitStickyOffset: 0, verticalPosition: "bottom", customVerticalPosition: true}`

Expected behaviour:
Bottom sticky snaps to bottom of view as soon as possible (i.e. snaps midway into parent element on page load).

**Comment by yowainwright** [comment]
This issue will require a demo or link to the web page you're working on. ~Thanks

**Comment by kvanberendonck** [comment]
Can still reproduce this with simple layout using blocks and no flex. I will plunkr this when I get some time to do so, but should be very easy to reproduce.

**Comment by yowainwright** [comment]
This could mean that the parent doesn't have a height.

If a parent element doesn't have a height b/c of its set styles, such as being `floated`, Stickybits will not be able to calculate when to be sticky and stuck. 

Here's another approach with `display: table`. I haven't tested it in multiple browsers but it gets away from `display: flex`.

Thanks to your notes, I should probably add notes to the readme!

However, in regards to this issue—it might lie with CSS (hopefully). 🙂

**Comment by kvanberendonck** [comment]
I haven't made the plunkr yet with an actual stickybits element for testing, but I tore out the exact page layout and put it here. The stickybit goes attached to top and bottom in the central element. https://jsfiddle.net/ceez49hy/14/

I will plunkr this as time allows.

**Comment by yowainwright** [comment]
I think this might be fixed ...?

I could use some help with the rest of these issues @donkeybonks ! 2.0 is out so it should be easy to debug and help! 

Let me know if you have time! 

~Thanks

**Comment by yowainwright** [comment]
Closing. ~Thanks
