### ISSUE TITLE
Should Stickybits provide a public `positionVal` for `position: sticky || fixed`?

### ISSUE THREAD

**Issue by cyr-x** [dollarshaveclub/stickybits#77]
I think it would be a good idea to add a boolean property to the stickyBits instance, which indicates if the plugin is using the native implementation of `position: sticky`.

This would allow users to simply check via JavaScript if the `position: fixed` "polyfill" is active or not, to for example apply additional styles dynamically.

I'm thinking of a property called `isNative` or `isUsingNative`. Also a property which indicates that the instance is using `position: fixed` would work (like for example: `isPolyfilled`).

**Comment by yowainwright** [comment]
@cyr-x thanks for your insight! 

Can you sell me on why this feature is necessary when every Stickybits element has an inline `position: sticky` of position: fixed` property? ~Thanks

**Comment by cyr-x** [comment]
Because it's a nice and simple way to check if it's using `position: sticky` or `position: fixed`. It would be easy implement this and because of this the user doesn't have to check manually if a style is set and possibly triggering some unwanted layout recalculation.

**Comment by yowainwright** [comment]
Could you provide a Codepen of how that feature could be beneficial over 1. the `position` set on the element by Stickybits or 2. checking the `positionVal` of the Stickybits instance? 

Pull Requests are also welcome. 💪

**Comment by cyr-x** [comment]
Here is a codepen with an example:
https://codepen.io/anon/pen/dzPGBN

**Comment by yowainwright** [comment]
This is 1 way: https://codepen.io/yowainwright/pen/VzLpQY. 
The other would be with css, like `.js-is-sticky[style*="position: sticky"]`

I appreciate what you're saying—to basically use Modernizr's _sticky check_. I tried to make the code slightly smaller by only addressing  elements affected by Stickybits.

**Comment by yowainwright** [comment]
Based on @cyr-x thoughtful notes: 

Should stickbits support public `sticky || fixed` out-of-the-box? (Or just provide notes in this issue)

- 👍  this comment if you want out-of-the-box support

**Comment by yowainwright** [comment]
@cyr-x I feel like "the people" want this! Thanks for your note. 🙏  

I will try to add this ASAP (next 2-3 days)

**Comment by yowainwright** [comment]
Done.

```javascript
var stickybit = stickybits('.thing');
var stickybit.positionVal
```
