### ISSUE TITLE
Ability to set the sticky offset in units other than px

### ISSUE THREAD

**Issue by kvanberendonck** [dollarshaveclub/stickybits#82]
For example, `rem` or `em`, would be really handy.

All my css sizing is done in `rem` so matching the sticky bit offset with the header size so it all collapses nicely is bit of a hacky guess at the moment.

**Comment by yowainwright** [comment]
Pixels are the unit of measure in the browser with javascript so it makes sense for Stickybits and other UI plugins to use pixels. If pixels are a concern for inline styles added by Stickybits, the engineer can do a calculation for another unit of measure after the stickybits parent element has the class `.js-stickybit-parent`.

**Comment by hacknug** [comment]
The problem with using pixels is that you'll always have to do the calculation you mentioned if your website uses only rem/em and scales for users that changed their browser's default font-size.

**Comment by yowainwright** [comment]
Stickybits adds a pixel number for the top offset only. If having inline px units for position styling is really an issue (which it will also be an issue for most [probably all] UI plugins—not just Stickybits 😊 ) the engineer can add the `customVerticalPosition` option and add their unit of measure with CSS. 

----

For note, pixels set inline on a single element shouldn't affect REMs, EMs, or Pts. If it does, that _might_ suggest deeper issues in the styling cascade. 💛

**Comment by kvanberendonck** [comment]
I might need to do some deep-diving to figure out what `customVerticalPosition` actually does .. I don't think it does what I thought it does.
