### ISSUE TITLE
Does not work on iOS devices

### ISSUE THREAD

**Issue by claytuna** [dollarshaveclub/stickybits#83]
None of the Codepen examples work on iPhone mobile safari. 

I tested the following on iPhone 6S, iPhone 7 - iOS version 10.3.3:

https://css-tricks.com/stickybits-alternative-position-sticky-polyfills/
https://codepen.io/yowainwright/pen/QdedaO
https://codepen.io/yowainwright/pen/VPogaX

**Comment by yowainwright** [comment]
Thanks for the note. 🙏 

That is not an issue with Stickybits. That's within Codepen, because the demos are in `<iframes>`.  I think that issues can be bypassed depending on how your viewing the example in Codepen.
