### ISSUE TITLE
Option to disable polyfill part of library

### ISSUE THREAD

**Issue by donkeybonks** [dollarshaveclub/stickybits#85]
I've realized that the way I use this library, it's basically only for the styling provided by the "sticky" and "stuck" classes. It's much easier to polyfill my app in css than relying on the classes added by the js because the css is more extensible.

The js is fighting against my stylesheets by overriding properties on the element in an attempt to implement the 'polyfill' but I don't really need it at all. I banged my css with `!important` everywhere to get rid of it, but a `disablePolyfill` on the options would be nice (it could be ligher on the client if it skips the polyfill part).

Also, ability to set the name of the classes `js-is-sticky` and such should be ony a 1-liner as it's already set using a `const`.

**Comment by kvanberendonck** [comment]
If I can get the OK here, I'll see if I can get some corporate time to raise a ton of PRs ..

**Comment by yowainwright** [comment]
Are you suggesting to remove the inline `position: value`?

Or, what specific inline css properties are you have a problem with?

**Comment by kvanberendonck** [comment]
Suggesting a way to not add these:
https://github.com/dollarshaveclub/stickybits/blob/master/src/stickybits.js#L111-L113

**Comment by yowainwright** [comment]
@kvanberendonck I will try to add this ASAP—next 2-3 days.

**Comment by kvanberendonck** [comment]
I'll PR this today

**Comment by rdennis** [comment]
This may be slightly off topic here, but for my use case I do not want `stickybits` to do anything at all if `position: sticky` is supported. My current workaround is to just use the built in polyfill logic before I call `stickybits`.

```js
(function () {
    var d = document.createElement('div');
    var prefixes = ['', '-o-', '-webkit-', '-moz-', '-ms-'];
    for (var i = 0, l = prefixes.length; i < l; i++) {
        d.style.position = prefixes[i] + 'sticky';
    }
    if (!d.style.position) {
        stickybits('.header');
    }
})();
```

Maybe this is an acceptable workaround, but it would be nice to have support for such a case.

**Comment by yowainwright** [comment]
Done with 2.0

**Comment by psntr** [comment]
Hi there,

Don't mean to re-open this case but where can I find this option in the documentation?  I just try to not run StickyBits if the browser doesn't support it. But if there is an native option I'd rather go with it.

**Comment by yowainwright** [comment]
@psntr it's been a bit. 😄  

Could you share a code snippet? ~Thanks
