### ISSUE TITLE
Doesn't work in Google Chrome 55

### ISSUE THREAD

**Issue by albv** [dollarshaveclub/stickybits#91]
None of provided codepen examples works in Google Chrome 55 on Ubuntu Linux. In Firefox all works as expected. 
Error in Chrome devtools console: 
` se.getBoundingClientRect is not a function at Stickybit.manageStickiness`

**Comment by yowainwright** [comment]
@albv I will look shortly. 

What version of Stickybits are you using? 🙏

**Comment by yowainwright** [comment]
@albv 

Just tested with the latest version of chrome here...

https://codepen.io/yowainwright/pen/5bf3b5d741cc783ee585a3d7c2765308/
https://codepen.io/yowainwright/pen/8a930892347c457f8db00d07ac44c356/

...And it looks like it's working as expected. 

I apologize. A bug was [released](https://github.com/dollarshaveclub/stickybits/commit/7b6c591052a0c26b7880c2de4567037e9c9e3d46) and then [fixed](https://github.com/dollarshaveclub/stickybits/commit/5bc76f54eb888348f95d670a356decef29135205)

Let me know if this note helps! 

~Thanks

**Comment by albv** [comment]
@yowainwright yes, I don't have this error with 1.5.3, thanks! But probably you need to update your Codepen examples, it seems they are still using the old version.
