### ISSUE TITLE
Classes not applied after refreshing scrolled page

### ISSUE THREAD

**Issue by hacknug** [dollarshaveclub/stickybits#93]
When refreshing a scrolled website, the browser automatically tries to keep your position. This causes stickybits not to apply its classes even if the option is set to true. I think classes should be there just as inline-styles are.

Here's a dev link where you can check this issue (http://dev.llos.co/cupofcouple/jessica-barensfeld-simon-howell/). If you want to see how the element gets stuck at the bottom you'll need to expand the comments section (just tap on the "Comments (N)" link to do that.

**Comment by kvanberendonck** [comment]
This is not because the class-setting code is failing but because the top of the element is computed incorrectly.

Same as Issue 2 that I mentioned here

https://github.com/dollarshaveclub/stickybits/issues/74#issuecomment-318249067

**Comment by kvanberendonck** [comment]
I used `getBoundingClientRect` recently and found the following in the documentation:

> The Element.getBoundingClientRect() method returns the size of an element and its position relative to the viewport.

What it fails to mention is that if the page is scrolled, the viewport is the `fixed` viewport not the page, so the elements `top` position is completely wrong. i.e. if you are scrolled halfway down a page, it returns something like `-1500` for `top`. The problem is somewhere in this interaction as when I console logged the guts of stickybits, the `stickyStop` and `stickyStart` values were wrong (issue #74)

**Comment by yowainwright** [comment]
Thanks for the insights @kvanberendonck and @hacknug ! I'm still not able to replicate the issue but I'm sure it IS there thanks to both of you! I knew how I would fix the issue before and didn't b/c I couldn't replicate it. I will work on this asap. 🙏

**Comment by VSG24** [comment]
Chrome 60 on macOS. Same problem.

**Comment by yowainwright** [comment]
@VSG24 Thanks for noting this. 🙏

**Comment by yowainwright** [comment]
@hacknug Okay, I think stickybits 2.0 can help here.

Could you reach out to me to help out?

**Comment by hacknug** [comment]
@yowainwright here I am

**Comment by yowainwright** [comment]
@hacknug saweet!

Okay, could make sure you're using Stickybits 2.0 on your dev site?
Then, instantiate Stickybits like this:
```javascript
var stickybit = stickybtis('selector') 
console.log(stickybit)
```
Once we get there, we can figure out how to update `stickyStart` and `stickyStop` (I think) 😜 ...or I will write a computed for those properties in Stickybits itself.

Here's an example for reference: https://codepen.io/yowainwright/pen/veZVPv

~Thanks

**Comment by yowainwright** [comment]
@hacknug I'm following up with this ticket @ #100
