### ISSUE TITLE
How can I detect when element is stuck to top of viewport?

### ISSUE THREAD

**Issue by matthewmcvickar** [dollarshaveclub/stickybits#95]
From what I can tell, the `js-is-sticky` class is added when the element gains the ability to stick, and the `js-is-stuck` class is added when the element sticks to the bottom of its parent. But how do we tell when the element has gotten stuck to the top of the viewport? I thought the `js-is-sticky` class indicated the element was stuck to the top of the viewport. But it only indicates the element's `position` is set to `sticky`.

I made this Codepen to demonstrate: https://codepen.io/matthewmcvickar/pen/VzbqLN

The green toolbar in that example gets the `js-is-sticky` class after the viewport has been scrolled a few pixels, but I don't want it to get that class until it starts sticking to the top of the viewport. Is this possible?

**[NOTE: This is a bug! I was right in my initial interpretation of what `js-is-sticky` means.]**

**[TL/DR: This happened because my sticky element wasn't the first child of its parent. Until this bug is fixed, I rearranged the HTML to wrap it differently as a workaround, and now this works.]**

**Comment by yowainwright** [comment]
@matthewmcvickar first, thank you for the clear question/issue! 🙏 

This issue is that because the sticky element is not the first child of its parent element, the `useStickyClasses` option doesn't calculate correctly. This will be fixed asap.

**Comment by kvanberendonck** [comment]
I believe it is a requirement with native sticky for the element to be the first child in the parent .. if not I have problems under Firefox.

**Comment by matthewmcvickar** [comment]
@yowainwright Aha, that is the problem! If I just put a wrapper around the whole page so that the toolbar is the first element, it works just fine. I'll use that as a workaround for the time being.

@kvanberendonck Hmm, I'm not seeing that. Here's a Codepen demo of non-first-children working just fine with native `position: sticky.` Works fine for me in Chrome, Safari, and Firefox.

**Comment by kvanberendonck** [comment]
Missing link

**Comment by matthewmcvickar** [comment]
@kvanberendonck Comment amended. I'm deleting this comment after I post it so you get your notification of it but it doesn't stick around. ;)

**Comment by kvanberendonck** [comment]
For example `element 3` in this fork doesn't work as expected even under Chrome unless it's the last element, top stickys seem to be working fine.

https://codepen.io/anon/pen/rzmgKa

**Comment by matthewmcvickar** [comment]
@kvanberendonck Ah, I see what you mean now. And as in this fork, there can be multiple bottom stickys as long as they aren't interrupted by a non-sticky element: https://codepen.io/anon/pen/mMmYGp

**Comment by yowainwright** [comment]
@matthewmcvickar Hopefully within the week. I apologize. The time-lapse is not intentional.

**Comment by matthewmcvickar** [comment]
@yowainwright Thank you for the update; I totally understand this is extra work for you. Can’t thank you enough! I’m using this on a few client projects and I'm eager for the update. :)

**Comment by yowainwright** [comment]
@matthewmcvickar I updated the original Codepen here. I changed the order of the dom. https://codepen.io/yowainwright/pen/rGwqee

Stickybits 2.0 was just pushed. 🙏

Sorry for the wait. Let me know how I can help. ~Thanks

**Comment by paolomoretti** [comment]
+1

**Comment by matthewmcvickar** [comment]
@yowainwright Wooo!! Thank you so much! That test Codepen looks good to me. Can we call this issue closed, or is #100 the same bug?

**Comment by yowainwright** [comment]
@matthewmcvickar thanks for following up!
