### ISSUE TITLE
Classes don't work when there are multiple stickybits on same scroll container

### ISSUE THREAD

**Issue by maxlapides** [dollarshaveclub/stickybits#96]
Here's a codepen that demonstrates the issue: https://codepen.io/maxlapides/pen/QMgQxZ

You'll notice as you scroll down that both Element 1 and Element 2 receive the `js-is-sticky` class even when only Element 1 is sticky.

**Comment by yowainwright** [comment]
Great observation! 

-  Something should be added to the `readme` to note that there should only be 1 sticky element per parent. 
-  Stickbits should return an error message if there are sibling Stickbits. 

Do you want to add this?

**Comment by kvanberendonck** [comment]
Regarding point 2, if you throw an error it will break my app that has both header and footer

**Comment by yowainwright** [comment]
@kvanberendonck "return an error message" => `console.warn`

**Comment by maxlapides** [comment]
@yowainwright Hey, sorry, i accidentally edited my pen above. Thanks for the note about only 1 sticky element per parent. That makes sense!

I do think I've uncovered a small bug, though, related to the sticky classes and `stickyBitStickyOffset`. When that offset value is > 0, the classes seem to not take that offset value into account. My above pen (https://codepen.io/maxlapides/pen/QMgQxZ) demonstrates this issue. You can see that the `js-is-sticky` class is only added to Element 2 when you scroll an additional 30px past when it becomes sticky.

**Comment by yowainwright** [comment]
@maxlapides thank, that was pointed out in another issue. I (or someone) will fix that asap. ~Thanks

**Comment by kvanberendonck** [comment]
Hmm, I came across a situation today where there were a lot of sticky elements (5 total) on a page setup to scroll as a 2-split (imagine a side-by-side pdf viewer).

One of the three headers didn't receive the classes but had no issues being sticky and wasn't in the same scroll container.

Just a note because I honestly don't think I will be able to reproduce in isolation..

**Comment by yowainwright** [comment]
#105

**Comment by yowainwright** [comment]
@maxlapides I re-ordered the dom a little bit and added the new version. 

https://codepen.io/yowainwright/pen/89d7ee21ce3d6bd8f5c06a7577ffda19/

Let me know if it helps! 

~Thanks
